### ISSUE TITLE
PropertyAccessException: Non-static method requires a target with one-to-one relations

### ISSUE THREAD

**Issue by fubar-coder** [nhibernate/nhibernate-core#1719]
It seems that there is a problem with one-to-one relations or my mapping.

Exception:

```text
Exception occurred getter of TestNhBug.FileEntry.Id
NHibernate.PropertyAccessException: Exception occurred getter of TestNhBug.FileEntry.Id ---> System.Reflection.TargetException: Non-static method requires a target.
   at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at NHibernate.Properties.BasicPropertyAccessor.BasicGetter.Get(Object target)
   --- End of inner exception stack trace ---
   at NHibernate.Properties.BasicPropertyAccessor.BasicGetter.Get(Object target)
   at NHibernate.Tuple.Entity.AbstractEntityTuplizer.GetIdentifier(Object entity)
   at NHibernate.Persister.Entity.AbstractEntityPersister.IsTransient(Object entity, ISessionImplementor session)
   at NHibernate.Engine.ForeignKeys.IsTransientFast(String entityName, Object entity, ISessionImplementor session)
   at NHibernate.Engine.ForeignKeys.IsTransientSlow(String entityName, Object entity, ISessionImplementor session)
   at NHibernate.Event.Default.DefaultDeleteEventListener.OnDelete(DeleteEvent event, ISet`1 transientEntities)
   at NHibernate.Impl.SessionImpl.FireDelete(DeleteEvent event, ISet`1 transientEntities)
   at NHibernate.Impl.SessionImpl.Delete(String entityName, Object child, Boolean isCascadeDeleteEnabled, ISet`1 transientEntities)
   at NHibernate.Engine.Cascade.CascadeOn(IEntityPersister persister, Object parent, Object anything)
   at NHibernate.Event.Default.AbstractFlushingEventListener.CascadeOnFlush(IEventSource session, IEntityPersister persister, Object key, Object anything)
   at NHibernate.Event.Default.AbstractFlushingEventListener.PrepareEntityFlushes(IEventSource session)
   at NHibernate.Event.Default.AbstractFlushingEventListener.FlushEverythingToExecutions(FlushEvent event)
   at NHibernate.Event.Default.DefaultAutoFlushEventListener.OnAutoFlush(AutoFlushEvent event)
   at NHibernate.Impl.SessionImpl.AutoFlushIfRequired(ISet`1 querySpaces)
   at NHibernate.Impl.SessionImpl.List(IQueryExpression queryExpression, QueryParameters queryParameters, IList results, Object filterConnection)
   at NHibernate.Impl.SessionImpl.List(IQueryExpression queryExpression, QueryParameters queryParameters, IList results)
   at NHibernate.Impl.AbstractSessionImpl.List(IQueryExpression queryExpression, QueryParameters parameters)
   at NHibernate.Impl.AbstractQueryImpl2.List()
   at NHibernate.Linq.DefaultQueryProvider.ExecuteQuery(NhLinqExpression nhLinqExpression, IQuery query, NhLinqExpression nhQuery)
   at NHibernate.Linq.DefaultQueryProvider.Execute(Expression expression)
   at NHibernate.Linq.DefaultQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.Single[TSource](IQueryable`1 source, Expression`1 predicate)
   at TestNhBug.Program.GetOrCreateEntry(ISession session, FileEntry parent, String name, Byte[] data) in c:\users\markjunker\source\repos\TestNhBug\TestNhBug\Program.cs:line 99
   at TestNhBug.Program.Main(String[] args) in c:\users\markjunker\source\repos\TestNhBug\TestNhBug\Program.cs:line 36
```

This are my mappings:

```xml
<?xml version="1.0" encoding="utf-8"?>
<hibernate-mapping
        assembly="TestNhBug"
        namespace="TestNhBug"
        xmlns="urn:nhibernate-mapping-2.2">
  <class name="FileEntry" table="filesystementries">
    <id name="Id" column="id" generator="assigned" />
    <property name="ParentId" column="parent_id" />
    <property name="Name" column="name" length="50" not-null="true" />
    <one-to-one name="Data" lazy="no-proxy" cascade="all-delete-orphan" />
  </class>
  <class name="FileData" table="filesystementrydata">
    <id name="Id" column="id">
      <generator class="foreign">
        <param name="property">Entry</param>
      </generator>
    </id>
    <property name="Data" column="data" not-null="true" type="BinaryBlob" lazy="true" />
    <one-to-one name="Entry" lazy="no-proxy" constrained="true" foreign-key="fk_data_entry" />
  </class>
</hibernate-mapping>
```

This is my test application:

```csharp
using System;
using System.Linq;
using System.Text;

using NHibernate;

namespace TestNhBug
{
    class Program
    {
        private static readonly Guid RootGuid = Guid.Parse("00000000-0000-0000-0000-000000000001");

        static void Main(string[] args)
        {
            var connectionString = @"Data Source=(LocalDb)\MSSQLLocalDB;Integrated Security=SSPI";
            var cfg = new NHibernate.Cfg.Configuration();
            cfg.SetProperty(NHibernate.Cfg.Environment.Dialect, "NHibernate.Dialect.MsSql2012Dialect");
            cfg.SetProperty(NHibernate.Cfg.Environment.ConnectionString, connectionString);
            cfg.AddAssembly(typeof(FileData).Assembly);

            var updater = new NHibernate.Tool.hbm2ddl.SchemaUpdate(cfg);
            updater.Execute(true, true);

            try
            {
                using (var sf = cfg.BuildSessionFactory())
                {
                    using (var session = sf.OpenSession())
                    {
                        using (var trans = session.BeginTransaction())
                        {
                            var rootEntry = GetOrCreateRootEntry(session);
                            GetOrCreateEntry(session, rootEntry, "text1.txt",
                                Encoding.UTF8.GetBytes("text1"));
                            var subEntry = GetOrCreateEntry(session, rootEntry, "test1");
                            GetOrCreateEntry(session, subEntry, "text1.txt",
                                Encoding.UTF8.GetBytes("text1 below test1"));

                            trans.Commit();
                        }
                    }
                }

                using (var sf = cfg.BuildSessionFactory())
                {
                    using (var session = sf.OpenSession())
                    {
                        using (var trans = session.BeginTransaction())
                        {
                            var entry = GetForPath(session, "test1", "text1.txt");

                            session.Delete(entry);
                            trans.Commit();
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                Console.Error.WriteLine(ex);
            }
        }

        private static FileEntry GetForPath(ISession session, params string[] path)
        {
            var found = session.Load<FileEntry>(RootGuid);
            foreach (var pathPart in path)
            {
                var next = session.Query<FileEntry>()
                    .Single(x => x.ParentId == found.Id && x.Name == pathPart);
                found = next;
            }

            return found;
        }

        private static FileEntry GetOrCreateRootEntry(ISession session)
        {
            var entry = session.Get<FileEntry>(RootGuid);

            if (entry != null)
                return entry;

            entry = new FileEntry()
            {
                Id = RootGuid,
                Name = string.Empty,
            };

            session.Save(entry);

            session.Flush();

            return entry;
        }

        private static FileEntry GetOrCreateEntry(ISession session, FileEntry parent, string name, byte[] data = null)
        {
            var entry = session.Query<FileEntry>()
                .SingleOrDefault(x => x.Name == name && x.ParentId == parent.Id);
            if (entry != null)
                return entry;

            entry = new FileEntry()
            {
                Id = Guid.NewGuid(),
                ParentId = parent.Id,
                Name = name,
            };

            FileData fileData;
            if (data != null)
            {
                fileData = new FileData
                {
                    Entry = entry,
                    Data = data,
                };

                entry.Data = fileData;
            }
            else
            {
                fileData = null;
            }

            session.Save(entry);

            if (fileData != null)
            {
                session.Save(fileData);
            }

            session.Flush();

            return entry;
        }
    }

    public class FileData
    {
        public virtual Guid Id { get; set; }
        public virtual byte[] Data { get; set; }
        public virtual FileEntry Entry { get; set; }
    }

    public class FileEntry
    {
        public virtual Guid Id { get; set; }
        public virtual Guid? ParentId { get; set; }
        public virtual string Name { get; set; }
        public virtual FileData Data { get; set; }
    }
}
```

**Comment by fredericDelaporte** [comment]
Does the issue still occurs if removing the `lazy="no-proxy"` from `FileData.Entry` mapping?

`no-proxy` is less useful on the constrained side. The constrained side mandates the other side to exists, so the default lazy mode can handle it by always yielding an un-initialized lazy-entity proxy without having to check the other side exists. (While on the non-constrained side, only `no-proxy` allows to lazy-load an one-to-one, by proxifying the owning entity into a lazy-property proxy, allowing to handle the case where the other side is missing. The `no-proxy` avoids proxifying the associated entity (into a lazy-entity proxy, interface `INHibernateProxy`), at the cost of proxifying the owning entity (into a lazy-property proxy, interface `IFieldInterceptorAccessor`).)

Having mapped both side with `no-proxy` causes them to be both instantiated as lazy-property proxies, which maybe triggers the issue. 

There is still a possible NHibernate issue too: it should not fail that way even if the mapping is maybe not adequate for your actual needs. (Unless I have missed a trouble in your code.)

**Comment by fubar-coder** [comment]
I created PR #1720 for this issue, but I'll also test your suggestion tomorrow.

**Comment by fubar-coder** [comment]
@fredericDelaporte I updated the PR but the problem still exists. Using "proxy" instead of "no-proxy" on both ends fixes this problem which indicates a problem with "no-proxy".

**Comment by hazzik** [comment]
This is either HHH-9663 or HHH-11965.

**Comment by hazzik** [comment]
Also, we would need to port this CS: https://github.com/hibernate/hibernate-orm/commit/2fc60011e5d2dacd875d98738dc911cf4f7983eb?w=1

**Comment by fredericDelaporte** [comment]
I was also looking into it, and for me, the bug is here:
https://github.com/nhibernate/nhibernate-core/blob/418d35aa18fac3d4d9b899e2bb9f4eeda0aa95d4/src/NHibernate/Cfg/MappingSchema/HbmOneToOne.cs#L83-L86
The property is not a lazy property when the entity is proxified. It is a lazy property when the entity is not proxified while having laziness still enabled thanks to `no-proxy`.

Switching this to `NoProxy` fix the test case. I have yet to check if this may cause any regression.

For me the test case trouble lies in the property being not flagged as lazy, causing the following code to be defeated:
https://github.com/nhibernate/nhibernate-core/blob/ee91396495a5e0874704f22c24ccde7412dafea0/src/NHibernate/Persister/Entity/AbstractEntityPersister.cs#L2551-L2570
This results in the loaded state having a proxy for the non-existent one-to-one end because `OneToOneType.Hydrate` always assume the other end exists, yielding the key of the owner as the key of the other end.

The Hibernate issues look to me as other one-to-one & cascade troubles.

**Comment by hazzik** [comment]
>I have yet to check if this may cause any regression.

It will be extremely hard to notice. Most likely all tests will pass, but the issues will be in the number of SQL queries generated.

**Comment by hazzik** [comment]
It also seems likely to me we have another kind of bug with many-to-one, but with the same root cause. I have to add more tests for ascertaining this.

Do you mean that?

https://github.com/nhibernate/nhibernate-core/blob/fb544b08199281b8d6597e48d46377c07ec505aa/src/NHibernate/Cfg/MappingSchema/HbmManyToOne.cs#L22-L25

**Comment by fredericDelaporte** [comment]
Yes.

**Comment by hazzik** [comment]
Yeah, it shall be NoProxy in both cases:

https://github.com/hibernate/hibernate-orm/blob/292a4e4337b336dd7c3a54a90c0582734eff07d4/hibernate-core/src/main/java/org/hibernate/mapping/Property.java#L237-L260

**Comment by fredericDelaporte** [comment]
But there is an issue with this change in `AbstractFieldInterceptor`. It seems to be implemented on the assumption that properties flagged as lazy are never an association, which is no more the case with my proposed changed. I am still analyzing this. (Maybe just switching some clauses will do, but I am still checking the code paths for now.)

> Most likely all tests will pass, but the issues will be in the number of SQL queries generated (For example, you'll get unexpected SELECT N+1 and similar weird stuff).

I do not see why this should happen more. Lazy properties and no-proxy are anyway always triggering n+1 loads situation, since their lazy fetch can not be batched (lazy fetch batching is implemented only for entity and collection laziness, not for property laziness). Flagging an association as `no-proxy` (or a property as lazy) is anyway acknowledging that n+1 loads will occurs if looping on a list of parent entities with an access to the association (or the property).

**Comment by fredericDelaporte** [comment]
Well, there is a quite a code smell in my opinion there. The fact that the loaded state was holding a proxy for an non-existing entity is expected by the current implementation, and is required for the `AbstractFieldInterceptor` current implementation. The interceptor uses that invalid proxy, calling its `Initialize`, which will try to load the entity. But instead of failing in case it does not exist, an additional flag (`unwrap`) causes it to no more check it has loaded nothing. Then the unwrapping on `AbstractFieldInterceptor` retrieves `null`.

Why not working like that for the proxy and the interceptor. But leaving an invalid proxy in the loaded state creates bugs for the dirty checking. It would be far more reliable for dirty checks to keep the "unloaded property object" in the loaded state instead of an unloaded proxy.

(By the way the `no-proxy` mode really does not honor well its name: not only it causes the owning entity to be proxified (as a lazy property proxy), but also it causes the associated entity to still be proxified, with a trick for hiding that.)

I consider touching only the one-to-one case, because this change has a drawback: the current pattern was causing the no-proxy to-one to be initialized on access without initializing the other lazy properties. (Lazy properties are instead all loaded simultaneously when one is accessed.) The change on the one-to-one will cause other lazy properties (if any) to initialize along the one-to-one, in a separated query. (If there is no lazy property excepted the one-to-one, no separated query is emitted.)

Performance-wise, this is a regression, but since it fixes a crash, it seems acceptable to me. (The full test suit now succeed with my local changes.)

The many-to-one case has not the one-to-one issues on dirty-checks, because the associated entity is guaranteed to actually exist (excepted non-enforced fk along with usage of the NH specific option `not-found`). Moreover flagging it as a lazy-property will very likely include its key in the lazy columns, causing it to be unknown at parent load time and requiring a lazy-property load even if there is no other lazy properties. So better keep it as it is currently.

Still I will have a look if instead of avoiding the code smell in the loaded state, it is doable to fix the dirty checking for supporting it at least in the case of this issue (hoping it does not cause troubles in other code paths).

**Comment by fredericDelaporte** [comment]
This trouble occurs when combining delete cascade with no-proxy non-constrained one-to-one and auto-flushes.
As a workaround, changing the flush mode for disabling auto-flushes would avoid the issue. But in such case, take care of manually flushing before querying entities which may be dirty in the session.

**Comment by hazzik** [comment]
So, you ended up extracting bits from the https://github.com/hibernate/hibernate-orm/commit/63e6793d8f8e4fa97466ec638dcdb3fee0b6cd73

**Comment by hazzik** [comment]
There are already issues for the "root cause": #806, #1087 and #1007

**Comment by fredericDelaporte** [comment]
I am in the process of closing #806 and #1087 because they are just expected behavior. I do not see how they relate to the trouble here. #1007 is yet another trouble, which I have indeed re-created locally (and fixed locally) when experimenting with flagging an association mapped with no-proxy as being a lazy property. But as you have seen by yourself, the current master does not have the issue.
