### ISSUE TITLE
1-N Issue on expectation : Could not synchronize database state with session

### ISSUE THREAD

**Issue by kYann** [nhibernate/nhibernate-core#1723]
Hi,

I have an entity User, wich have a list of ChatIdentifier. When trying to perform a Flush of the session, the ChatIdentifier is INSERTED and then UPDATED for the foreign key. 
Update should work fine (user_id exist in database), but instead I get a StaleStateException :/.

INSERT INTO qa.chat_identifier (value, chat_service) VALUES (:p0, :p1); select lastval();:p0 = 'ZZZZZZ', :p1 = 'Slack'
UPDATE qa.chat_identifier SET user_id = :p0 WHERE Id = :p1;:p0 = 6f965b59-9759-4d37-ad59-a8f2010c22a4 :p1 = 57

NHibernate.Event.Default.AbstractFlushingEventListener:Error: Could not synchronize database state with session

NHibernate.StaleStateException: Unexpected row count: 0; expected: 1
   at NHibernate.AdoNet.Expectations.BasicExpectation.VerifyOutcomeNonBatched(Int32 rowCount, DbCommand statement)
   at NHibernate.Persister.Collection.AbstractCollectionPersister.PerformInsert(Object ownerId, IPersistentCollection collection, IExpectation expectation, Object entry, Int32 index, Boolean useBatch, Boolean callable, ISessionImplementor session)
   at NHibernate.Persister.Collection.AbstractCollectionPersister.InsertRows(IPersistentCollection collection, Object id, ISessionImplementor session)
   at NHibernate.Action.CollectionUpdateAction.Execute()
   at NHibernate.Engine.ActionQueue.InnerExecute(IExecutable executable)
   at NHibernate.Engine.ActionQueue.ExecuteActions(IList list)
   at NHibernate.Engine.ActionQueue.ExecuteActions()
   at NHibernate.Event.Default.AbstractFlushingEventListener.PerformExecutions(IEventSource session)

**Comment by fredericDelaporte** [comment]
Hello,
It is quite unlikely someone will diagnose this with the information supplied. Please elaborate a failing test case. See [Contributing](https://github.com/nhibernate/nhibernate-core/blob/master/CONTRIBUTING.md).

**Comment by kYann** [comment]
Hello,

Fixed, I was missing a flush before completing the session (no dispose made also).

Thanks,
