### ISSUE TITLE
TimeSpanType formula sometime crashes with an arithmetic overflow

### ISSUE THREAD

**Issue by mminkov** [nhibernate/nhibernate-core#1780]
Selecting an entity with a computed by formula `TimeSpanType` property sometime crashes with "Arithmetic operation resulted in an overflow."

The crash depends of entity calculated value.
e.g. when calculate value is:
- 00:01:24 => no exception
- 00:03:11 => no exception
- 00:01:25 => exception appear

The crash was reproduced with NHibernate 4.1.x, using Oracle.DataAccess.dll (v.10.2.0.100)

Code snippet to reproduce the crash:
```c#
    [TestFixture]
    public class Fixture : BugTestCase
    {
        protected override void OnSetUp()
        {
            using (var session = OpenSession())
            using (var transaction = session.BeginTransaction())
            {
                var e1 = new Entity
                {
                    Name = "Test1",
                    StartedAt = new DateTime(2018, 7, 2, 20, 0, 0),
                    CompletedAt = new DateTime(2018, 7, 2, 20, 1, 24)
                };
                e1.Duration = e1.CompletedAt - e1.StartedAt;
                session.Save(e1);

                var e2 = new Entity
                {
                    Name = "Test2",
                    StartedAt = new DateTime(2018, 7, 2, 20, 0, 0),
                    CompletedAt = new DateTime(2018, 7, 2, 20, 3, 11)
                };
                e2.Duration = e2.CompletedAt - e2.StartedAt;
                session.Save(e2);

                var e3 = new Entity
                {
                    Name = "Test3",
                    StartedAt = new DateTime(2018, 7, 2, 20, 0, 0),
                    CompletedAt = new DateTime(2018, 7, 2, 20, 1, 25)
                };
                e3.Duration = e3.CompletedAt - e3.StartedAt;
                session.Save(e3);

                session.Flush();
                transaction.Commit();
            }
        }

        protected override void OnTearDown()
        {
            using (var session = OpenSession())
            using (var transaction = session.BeginTransaction())
            {
                session.Delete("from System.Object");

                session.Flush();
                transaction.Commit();
            }
        }

        [Test]
        public void YourTestName()
        {
            using (var session = OpenSession())
            using (session.BeginTransaction())
            {
                var entities = (from e in session.Query<Entity>()
                                where e.Name == "Test1"
                                select e).ToList();

                Assert.AreEqual(1, entities.Count);

                entities = (from e in session.Query<Entity>()
                            where e.Name == "Test2"
                            select e).ToList();

                Assert.AreEqual(1, entities.Count);

                entities = (from e in session.Query<Entity>()
                            where e.Name == "Test3"
                            select e).ToList();

                Assert.AreEqual(1, entities.Count);
            }
        }
    }
```

Stacktrace:
```
NHibernate.Exceptions.GenericADOException crossed a native/managed boundary
  HResult=-2146232832
  Message=could not execute query
[ select entity0_.Id as Id1_0_, entity0_.Name as Name2_0_, entity0_.StartedAt as Starte3_0_, entity0_.CompletedAt as Comple4_0_, ((cast(entity0_.COMPLETEDAT as date)-cast(entity0_.STARTEDAT as date))*24*60*60*10000000) as formula0_ from Entity entity0_ 

where entity0_.Name=:p0 ]
  Name:p1 - Value:Test3
[SQL: select entity0_.Id as Id1_0_, entity0_.Name as Name2_0_, entity0_.StartedAt as Starte3_0_, entity0_.CompletedAt as Comple4_0_, ((cast(entity0_.COMPLETEDAT as date)-cast(entity0_.STARTEDAT as date))*24*60*60*10000000) as formula0_ from Entity entity0_ 

where entity0_.Name=:p0]
  Source=NHibernate
  SqlString=select entity0_.Id as Id1_0_, entity0_.Name as Name2_0_, entity0_.StartedAt as Starte3_0_, entity0_.CompletedAt as Comple4_0_, ((cast(entity0_.COMPLETEDAT as date)-cast(entity0_.STARTEDAT as date))*24*60*60*10000000) as formula0_ from Entity 

entity0_ where entity0_.Name=:p0
  StackTrace:
       at NHibernate.Loader.Loader.DoList(ISessionImplementor session, QueryParameters queryParameters, IResultTransformer forcedResultTransformer)
       at NHibernate.Loader.Loader.DoList(ISessionImplementor session, QueryParameters queryParameters)
       at NHibernate.Loader.Loader.ListIgnoreQueryCache(ISessionImplementor session, QueryParameters queryParameters)
       at NHibernate.Loader.Loader.List(ISessionImplementor session, QueryParameters queryParameters, ISet`1 querySpaces, IType[] resultTypes)
       at NHibernate.Loader.Hql.QueryLoader.List(ISessionImplementor session, QueryParameters queryParameters)
       at NHibernate.Hql.Ast.ANTLR.QueryTranslatorImpl.List(ISessionImplementor session, QueryParameters queryParameters)
       at NHibernate.Engine.Query.HQLQueryPlan.PerformList(QueryParameters queryParameters, ISessionImplementor session, IList results)
       at NHibernate.Impl.SessionImpl.List(IQueryExpression queryExpression, QueryParameters queryParameters, IList results)
       at NHibernate.Impl.AbstractSessionImpl.List(IQueryExpression queryExpression, QueryParameters parameters)
       at NHibernate.Impl.AbstractQueryImpl2.List()
       at NHibernate.Linq.DefaultQueryProvider.ExecuteQuery(NhLinqExpression nhLinqExpression, IQuery query, NhLinqExpression nhQuery)
       at NHibernate.Linq.DefaultQueryProvider.Execute(Expression expression)
       at NHibernate.Linq.DefaultQueryProvider.Execute[TResult](Expression expression)
       at Remotion.Linq.QueryableBase`1.GetEnumerator()
       at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
       at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
       at NHibernate.Test.NHSpecificTest.NH0000.Fixture.YourTestName() in D:\LogSys Development\Baseline\nhibernate\nhibernate-core-testcase-master\NHSpecificTest\NH0000\Fixture.cs:line 80
  InnerException: System.OverflowException
       HResult=-2146233066
       Message=Arithmetic operation resulted in an overflow.
       Source=Oracle.DataAccess
       StackTrace:
            at Oracle.DataAccess.Types.DecimalConv.GetDecimal(IntPtr numCtx)
            at Oracle.DataAccess.Client.OracleDataReader.GetDecimal(Int32 i)
            at Oracle.DataAccess.Client.OracleDataReader.GetValue(Int32 i)
            at Oracle.DataAccess.Client.OracleDataReader.get_Item(Int32 i)
            at NHibernate.Type.TimeSpanType.Get(IDataReader rs, Int32 index)
            at NHibernate.Type.NullableType.NullSafeGet(IDataReader rs, String name)
            at NHibernate.Type.NullableType.NullSafeGet(IDataReader rs, String[] names, ISessionImplementor session, Object owner)
            at NHibernate.Type.AbstractType.Hydrate(IDataReader rs, String[] names, ISessionImplementor session, Object owner)
            at NHibernate.Persister.Entity.AbstractEntityPersister.Hydrate(IDataReader rs, Object id, Object obj, ILoadable rootLoadable, String[][] suffixedPropertyColumns, Boolean allProperties, ISessionImplementor session)
            at NHibernate.Loader.Loader.LoadFromResultSet(IDataReader rs, Int32 i, Object obj, String instanceClass, EntityKey key, String rowIdAlias, LockMode lockMode, ILoadable rootPersister, ISessionImplementor session)
            at NHibernate.Loader.Loader.InstanceNotYetLoaded(IDataReader dr, Int32 i, ILoadable persister, EntityKey key, LockMode lockMode, String rowIdAlias, EntityKey optionalObjectKey, Object optionalObject, IList hydratedObjects, ISessionImplementor 

session)
            at NHibernate.Loader.Loader.GetRow(IDataReader rs, ILoadable[] persisters, EntityKey[] keys, Object optionalObject, EntityKey optionalObjectKey, LockMode[] lockModes, IList hydratedObjects, ISessionImplementor session)
            at NHibernate.Loader.Loader.GetRowFromResultSet(IDataReader resultSet, ISessionImplementor session, QueryParameters queryParameters, LockMode[] lockModeArray, EntityKey optionalObjectKey, IList hydratedObjects, EntityKey[] keys, Boolean 

returnProxies, IResultTransformer forcedResultTransformer)
            at NHibernate.Loader.Loader.DoQuery(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer)
            at NHibernate.Loader.Loader.DoQueryAndInitializeNonLazyCollections(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer)
            at NHibernate.Loader.Loader.DoList(ISessionImplementor session, QueryParameters queryParameters, IResultTransformer forcedResultTransformer)
```

Mapped class:
```c#
class Entity
{
        public virtual Guid Id { get; set; }

        public virtual string Name { get; set; }

        public virtual DateTime? StartedAt { get; set; }

        public virtual DateTime? CompletedAt { get; set; }

        public virtual TimeSpan? Duration { get; set; }
}
```

Mapping files:
```xml
  <class name="Entity">
    <id name="Id" generator="guid.comb" />
    <property name="Name" />
    <property name="StartedAt" />
    <property name="CompletedAt" />
    <property name="Duration" insert="false" update="false" formula="((cast(COMPLETEDAT as date)-cast(STARTEDAT as date))*24*60*60*10000000)" />
  </class>
```

**Comment by fredericDelaporte** [comment]
The trouble likely lies here: `Oracle.DataAccess.Client.OracleDataReader.GetDecimal(Int32 i)`.
Your formula yields a result that the Oracle data provider try to read as a `decimal`. This is not a good thing since `TimeSpanType` expects an `Int64` instead. Try add a cast into your formula.

As for why an arithmetic overflow occurs within the Oracle data provider when attempting to read some values as decimal, I do not know. (I would guess it has actually get something more like a double, which does not preserve fractional digits accuracy and can generates many of them on some values due to this. It then causes the number to have more digits than what a decimal can handle.)
Anyway that entirely looks as an external issue, not bounded to NHibernate.
