### ISSUE TITLE
Nhibernate throws error 'Invalid attempt to read when no data is present.' when using FetchMany and logging Trace messages to Microsoft.Extensions.Logging.ILogger

### ISSUE THREAD

**Issue by DaEkstrim** [nhibernate/nhibernate-core#1805]
Hi all, first time logging an issue, so please bear with me.

My environment:
FluentNhibernate: 2.1.2 (it's not related to FluentNhibernate though)
NHibernate: 5.1.1
DotNet Core: 2.1.0
Datbase: SQL Server 2017
App Type: Console Application (see the issue reproduction project)

I have to admit, that this error has bewildered me for a whole week trying to narrow down, but it is what the title says. When performing a query, using the FetchMany (doesn't happen on Fetch or when using neither), and the NhibernateLogger is designed to log to the Console through Microsoft's logging implementation, Nhibernate throws an error stating ""Invalid attempt to read when no data is present.". If the line setting the NhibernateLogger is commented out or the log level is raised to info, the error no longer occurs.

Error stack:
```
System.InvalidOperationException: Invalid attempt to read when no data is present.
   at System.Data.SqlClient.SqlDataReader.CheckHeaderIsReady(Int32 columnIndex, Boolean permitAsync, String methodName)
   at System.Data.SqlClient.SqlDataReader.IsDBNull(Int32 i)
   at NHibernate.Type.NullableType.NullSafeGet(DbDataReader rs, String name, ISessionImplementor session)
   at NHibernate.Type.ManyToOneType.Hydrate(DbDataReader rs, String[] names, ISessionImplementor session, Object owner)
   at NHibernate.Type.EntityType.NullSafeGet(DbDataReader rs, String[] names, ISessionImplementor session, Object owner)
   at NHibernate.Collection.Generic.PersistentGenericBag`1.ReadFrom(DbDataReader reader, ICollectionPersister role, ICollectionAliases descriptor, Object owner)
   at NHibernate.Loader.Loader.ReadCollectionElement(Object optionalOwner, Object optionalKey, ICollectionPersister persister, ICollectionAliases descriptor, DbDataReader rs, ISessionImplementor session)
   at NHibernate.Loader.Loader.ReadCollectionElements(Object[] row, DbDataReader resultSet, ISessionImplementor session)
   at NHibernate.Loader.Loader.GetRowFromResultSet(DbDataReader resultSet, ISessionImplementor session, QueryParameters queryParameters, LockMode[] lockModeArray, EntityKey optionalObjectKey, IList hydratedObjects, EntityKey[] keys, Boolean returnProxies, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.DoQuery(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.DoQueryAndInitializeNonLazyCollections(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.DoList(ISessionImplementor session, QueryParameters queryParameters, IResultTransformer forcedResultTransformer)

```
Since there's too many variables, this error is hard to explain and reproducing it through an explanation is down right impossible, I have created a simple Console application which reproduces this error (at least on my and my colleague's machine it does). You can find it at: https://github.com/DaEkstrim/BugReport.Nhibernate.FetchManyLogging

The SQL script to generate the table structure required for the test is included in the project.

If I can provide you with any additional information please let me know.

**Comment by bahusoid** [comment]
Big chance the cause is the same as in #1667 which was fixed in 5.1.2. Can you reproduce the issue on the latest 5.1.3 version?

**Comment by hazzik** [comment]
Should be the same.

**Comment by DaEkstrim** [comment]
You are right. Not reproducible using Nhibernate 5.1.3. It seems the question I should have asked myself before investing a whole week into this is "have you tried turning it off and on again?" or in this case 'updated to the latest version?'.

Thanks guys. Case closed.

**Comment by hazzik** [comment]
Duplicate of #1667
