### ISSUE TITLE
Initializing[XXXXXXX#1915584516]-Could not initialize proxy - no Session.

### ISSUE THREAD

**Issue by VBVCoder** [nhibernate/nhibernate-core#1807]
We have upgraded Nhibernate from 2.1.2 to 5.1.3. Internally, we are using unit wrappers to manage sessions. But when we accessing one of the entity which has child entity then we are receiving Initializing[XXXXXXX#1915584516]-Could not initialize proxy - no Session and sometimes Lazy-initialization exception. 

Here is stack trace.

at NHibernate.ByteCode.Castle.ProxyFactory.GetProxy(Object id, ISessionImplementor session)
   at NHibernate.Tuple.Entity.AbstractEntityTuplizer.CreateProxy(Object id, ISessionImplementor session)
   at NHibernate.Persister.Entity.AbstractEntityPersister.CreateProxy(Object id, ISessionImplementor session)
   at NHibernate.Event.Default.DefaultLoadEventListener.CreateProxyIfNecessary(LoadEvent event, IEntityPersister persister, EntityKey keyToLoad, LoadType options, IPersistenceContext persistenceContext)
   at NHibernate.Event.Default.DefaultLoadEventListener.ProxyOrLoad(LoadEvent event, IEntityPersister persister, EntityKey keyToLoad, LoadType options)
   at NHibernate.Event.Default.DefaultLoadEventListener.OnLoad(LoadEvent event, LoadType loadType)
   at NHibernate.Impl.SessionImpl.FireLoad(LoadEvent event, LoadType loadType)
   at NHibernate.Impl.SessionImpl.InternalLoad(String entityName, Object id, Boolean eager, Boolean isNullable)
   at NHibernate.Type.EntityType.ResolveIdentifier(Object id, ISessionImplementor session)
   at NHibernate.Type.EntityType.ResolveIdentifier(Object value, ISessionImplementor session, Object owner)
   at NHibernate.Engine.TwoPhaseLoad.InitializeEntity(Object entity, Boolean readOnly, ISessionImplementor session, PreLoadEvent preLoadEvent, PostLoadEvent postLoadEvent)
   at NHibernate.Loader.Loader.InitializeEntitiesAndCollections(IList hydratedObjects, Object resultSetId, ISessionImplementor session, Boolean readOnly)
   at NHibernate.Loader.Loader.DoQuery(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.DoQueryAndInitializeNonLazyCollections(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.DoList(ISessionImplementor session, QueryParameters queryParameters, IResultTransformer forcedResultTransformer)
  at NHibernate.Loader.Loader.ListIgnoreQueryCache(ISessionImplementor session, QueryParameters queryParameters)
   at NHibernate.Loader.Loader.List(ISessionImplementor session, QueryParameters queryParameters, ISet`1 querySpaces)
   at NHibernate.Impl.SessionImpl.List(CriteriaImpl criteria, IList results)
   at NHibernate.Impl.CriteriaImpl.List(IList results)
   at NHibernate.Impl.CriteriaImpl.UniqueResult[T]()

When we degraded to 3.4.1.4000, we are not facing any issue. So Please let us know, Is it issue with latest version or else please provide a solution.

**Comment by bahusoid** [comment]
>at NHibernate.ByteCode.Castle.ProxyFactory.GetProxy(Object id, ISessionImplementor session)

This seems like exception from external code. I suspect Castle bytecode provider is simply doesn't support NHibernate 5x.
If you don't have any specific code relying on Castle  just try to remove it from NHibernate configuration and let it use default provider.

**Comment by VBVCoder** [comment]
Thanks for the quick response.

I tried by removing the Nhibernate.ByteCode.Castle.dll reference still getting same issue. below is the error details.

**Error Massage:** Initializing[Upp.Irms.Domain.ReportParameter#1915584516]-Could not initialize proxy - no Session.

**Stack Trace:**
 at NHibernate.Proxy.AbstractLazyInitializer.Initialize()
   at NHibernate.Proxy.AbstractLazyInitializer.GetImplementation()
   at ReportParameterProxy.get_Parameter()

we also tried with below two settings but no use:

- <property name="proxyfactory.factory_class">NHibernate.Bytecode.StaticProxyFactoryFactory, NHibernate</property>     

- <property name="proxyfactory.factory_class">NHibernate.Bytecode.DefaultProxyFactoryFactory, NHibernate</property>

**Comment by VBVCoder** [comment]
Thanks for the quick response.

I tried by removing the Nhibernate.ByteCode.Castle.dll reference still getting same issue. below is the error details.

Error Massage: Initializing[Upp.Irms.Domain.ReportParameter#1915584516]-Could not initialize proxy - no Session.

Stack Trace:
at NHibernate.Proxy.AbstractLazyInitializer.Initialize()
at NHibernate.Proxy.AbstractLazyInitializer.GetImplementation()
at ReportParameterProxy.get_Parameter()

we also tried with below two settings for proxyfactory.factory_class but no use:

NHibernate.Bytecode.StaticProxyFactoryFactory, NHibernate

NHibernate.Bytecode.DefaultProxyFactoryFactory, NHibernate

**Comment by bahusoid** [comment]
Yeah it's really hard to say what's wrong without unit test. You might be suffering from 2 different issues:
1) Castle is not supported by NHiberante 5.x;
2) Different behavior of Castle implementation for lazy not initialized entities.

As from you last stack trace it seems you are accessing lazy entity outside of session context. And it's not supported by new proxy implementation.
Can you still reproduce the first exception (initiated from NHibernate.Impl.CriteriaImpl.UniqueResult)?

**Comment by VBVCoder** [comment]
We will create unit test. As It is old architecture(7 years old) and it was using Nhibernate older version. As newer version  we are getting issues at core level. We need to create a use case as per current design and it will take some time. Anyway, we will come up with use case where issue is reproducible and we will seek your inputs.
