### ISSUE TITLE
Custom Nullable Type ORA-00932  inconsistent datatypes

### ISSUE THREAD

**Issue by gokhanabatay** [nhibernate/nhibernate-core#1919]
With custom user type; 
Short Date' are stored in database as integer 
But Entity level it's stored as DateTime?.
We are also using OData for custom order by , skip,top,select etc but i think it's not the case.

Below sql shows that NHLinq2Sql checks nullable to order them first at order by and sends null parameter with TimeSpan parameter, this parameter needs to be integer, because SqlNumberDate.SqlTypes is DbType.Int32

```sql
order by memberdefi0_.MBR_ID asc, (case when memberdefi0_.INSTALLATION_DATE is null then :p0 else memberdefi0_.INSTALLATION_DATE end) asc;:p0 = NULL [Type: DateTime (0:0:0)]
```

```c#
[Serializable]
    public class SqlNumberDate : IUserType
    {
        protected virtual string Format { get; } = "yyyyMMdd";

        /// <summary>
        /// Compare two instances of the class mapped by this type for persistent "equality"
        ///             ie. equality of persistent state
        /// </summary>
        /// <param name="x"/><param name="y"/>
        /// <returns/>
        public new bool Equals(object x, object y)
        {
            if (x == y) return true;
            if (x == null || y == null) return false;
            DateTime? l = (DateTime?)x;
            DateTime? r = (DateTime?)y;

            return l.Equals(r);
        }

        /// <summary>
        /// Get a hashcode for the instance, consistent with persistence "equality"
        /// </summary>
        public int GetHashCode(object x)
        {
            DateTime? value = (DateTime?)x;

            return value.GetHashCode();
        }

        /// <summary>
        /// Retrieve an instance of the mapped class from a JDBC resultset.
        ///             Implementors should handle possibility of null values.
        /// </summary>
        /// <param name="rs">a IDataReader</param><param name="names">column names</param><param name="owner">the containing entity</param>
        /// <returns/>
        /// <exception cref="T:NHibernate.HibernateException">HibernateException</exception>
        public object NullSafeGet(DbDataReader rs, string[] names, ISessionImplementor session, object owner)
        {
            object result = NHibernateUtil.String.NullSafeGet(rs, names[0], session, owner);

            if (result == null)
                return default(DateTime?);
            else
            {
                DateTime.TryParseExact(result.ToString(), Format, null, System.Globalization.DateTimeStyles.None, out var date);
                return date;
            }
        }

               /// <summary>
        /// Write an instance of the mapped class to a prepared statement.
        ///             Implementors should handle possibility of null values.
        ///             A multi-column type should be written to parameters starting from index.
        /// </summary>
        /// <param name="cmd">a IDbCommand</param><param name="value">the object to write</param><param name="index">command parameter index</param><exception cref="T:NHibernate.HibernateException">HibernateException</exception>
        public override void NullSafeSet(DbCommand cmd, object value, int index, ISessionImplementor session)
        {
            Int32? result = value != null ? Int32.Parse(((DateTime?)value).Value.ToString(Format)) : default(Int32?);

            NHibernateUtil.Int32.NullSafeSet(cmd, result, index, session);
        }

        /// <summary>
        /// The SQL types for the columns mapped by this type. 
        /// </summary>
        public override SqlType[] SqlTypes
        {
            get
            {
                return new[] { new SqlType(DbType.Int32) };
            }
        }

        /// <summary>
        /// Return a deep copy of the persistent state, stopping at entities and at collections.
        /// </summary>
        /// <param name="value">generally a collection element or entity field</param>
        /// <returns>
        /// a copy
        /// </returns>
        public object DeepCopy(object value)
        {
            return value;
        }

        /// <summary>
        /// During merge, replace the existing (<paramref name="target"/>) value in the entity
        ///             we are merging to with a new (<paramref name="original"/>) value from the detached
        ///             entity we are merging. For immutable objects, or null values, it is safe to simply
        ///             return the first parameter. For mutable objects, it is safe to return a copy of the
        ///             first parameter. For objects with component values, it might make sense to
        ///             recursively replace component values.
        /// </summary>
        /// <param name="original">the value from the detached entity being merged</param><param name="target">the value in the managed entity</param><param name="owner">the managed entity</param>
        /// <returns>
        /// the value to be merged
        /// </returns>
        public object Replace(object original, object target, object owner)
        {
            return DeepCopy(original);
        }

        /// <summary>
        /// Reconstruct an object from the cacheable representation. At the very least this
        ///             method should perform a deep copy if the type is mutable. (optional operation)
        /// </summary>
        /// <param name="cached">the object to be cached</param><param name="owner">the owner of the cached object</param>
        /// <returns>
        /// a reconstructed object from the cachable representation
        /// </returns>
        public object Assemble(object cached, object owner)
        {
            return DeepCopy(cached);
        }

        /// <summary>
        /// Transform the object into its cacheable representation. At the very least this
        ///             method should perform a deep copy if the type is mutable. That may not be enough
        ///             for some implementations, however; for example, associations must be cached as
        ///             identifier values. (optional operation)
        /// </summary>
        /// <param name="value">the object to be cached</param>
        /// <returns>
        /// a cacheable representation of the object
        /// </returns>
        public object Disassemble(object value)
        {
            return DeepCopy(value);
        }

        /// <summary>
        /// The type returned by <c>NullSafeGet()</c>
        /// </summary>
        public Type ReturnedType
        {
            get { return typeof(DateTime?); }
        }

        /// <summary>
        /// Are objects of this type mutable?
        /// </summary>
        public bool IsMutable
        {
            get { return false; }
        }
    }
```

```
2018-12-04 14:23:21.0260| 125|DEBUG|b935bd6587fa4d0782d5b2420d365031|NHibernate.SQL|select memberdefi0_.MBR_ID as mbr1_41_, memberdefi0_.LAST_UPDATED as last2_41_, memberdefi0_.DESCRIPTION as description3_41_  from MYSCHEMA.MEMBER_DEFINITION memberdefi0_ order by memberdefi0_.MBR_ID asc, (case when memberdefi0_.INSTALLATION_DATE is null then :p0 else memberdefi0_.INSTALLATION_DATE end) asc;:p0 = NULL [Type: DateTime (0:0:0)]
2018-12-04 14:23:21.0440| 125|ERROR|b935bd6587fa4d0782d5b2420d365031|NHibernate.AdoNet.AbstractBatcher|Could not execute query: select memberdefi0_.MBR_ID as mbr1_41_, memberdefi0_.LAST_UPDATED as last2_41_, memberdefi0_.DESCRIPTION as description3_41_ from MYSCHEMA.MEMBER_DEFINITION memberdefi0_ order by memberdefi0_.MBR_ID asc, (case when memberdefi0_.INSTALLATION_DATE is null then :p0 else memberdefi0_.INSTALLATION_DATE end) asc
Oracle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-00932: tutarsız veri türleri: olması gereken: TIMESTAMP alınan: NUMBER
   at OracleInternal.ServiceObjects.OracleConnectionImpl.VerifyExecution(Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, SqlStatementType sqlStatementType, Int32 arrayBindCount, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
   at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteReader(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, OracleDataReaderImpl& rdrImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[] scnForExecution, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, Int64& internalInitialLOBFS, OracleException& exceptionForArrayBindDML, OracleConnection connection, OracleLogicalTransaction& oracleLogicalTransaction, IEnumerable`1 adrianParsedStmt, Boolean isDescribeOnly, Boolean isFromEF)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteReader(Boolean requery, Boolean fillRequest, CommandBehavior behavior)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at NHibernate.AdoNet.AbstractBatcher.ExecuteReader(DbCommand cmd)
```

**Comment by hazzik** [comment]
>this parameter needs to be integer, because SqlNumberDate.SqlTypes is DbType.Int32

However, the database says that it expects TIMESTAMP and received NUMBER:

> ORA-00932: tutarsız veri türleri: olması gereken: TIMESTAMP alınan: NUMBER

Google translation:
>ORA-00932: Inconsistent data types: Must be: TIMESTAMP Received: NUMBER

**Comment by gokhanabatay** [comment]
You are right @hazzik  but in database its stored number for sure.

Could it be?
IDbDataParameter.DbType = TimeStamp or DateTime but the value is null so it fails.
I try this sql with Toad and set Type of field to Date and the value is null(empty) then I get the same error.

ORA-00932: inconsistent datatypes: expected DATE got NUMBER

**Comment by fredericDelaporte** [comment]
As pointed by Alexander, the database actually receives a number, but reject it. That is not a trouble of the custom type, that is a trouble to debug on the DB side.

This said, this place here is not for support. Please consider elaborating a proper test case (see [contributing](https://github.com/nhibernate/nhibernate-core/blob/master/CONTRIBUTING.md)) when you think there is a bug in NHibernate, before opening an issue here. Frequently, this will even help yourself solve the issue.

**Comment by gokhanabatay** [comment]
Hi @fredericDelaporte I try to simulate as I can and I debug NH code.
for the order parameter :p0 "parameterNode.HqlParameterSpecification.ExpectedType = null" I think for that 
Command DbType setted to DateTime and corresponding OracleDbType is TimeSpan but it needs to be int?. 

![image](https://user-images.githubusercontent.com/9988911/49482384-f7dec500-f83f-11e8-9b3e-cdd58f674af4.png)

```c#
            //no problem gets the result 
            var successfullRetrieve = ISession.Query<MemberDefinition>().OrderBy(x => x.InstallationDate).ToList();
            //fails because I want nulls first, and OData creates expression like below
            var failureRetrieve = ISession.Query<MemberDefinition>().OrderBy(x => x.InstallationDate == null ? null : x.InstallationDate).ToList();
```

Please check this scenario;
```c#
public class MemberDefinition 
    {
        public MemberDefinition() { }
        public virtual short MbrId { get; set; }
        public virtual long LastUpdated { get; set; }
        public virtual string Description { get; set; }
        public virtual string LanguageCode { get; set; }
        public virtual short MbrCurrency { get; set; }
        public virtual **DateTime?** InstallationDate { get; set; }
    }

public class MemberDefinitionMap : ClassMap<MemberDefinition>
    {
        public MemberDefinitionMap()
        {
            Schema("MYSCHEMA");
            Table("MEMBER_DEFINITION");
            Id(x => x.MbrId).Column("MBR_ID").GeneratedBy.Increment();
            Map(x => x.Description).Column("DESCRIPTION").Not.Nullable().Length(100);
            Map(x => x.LanguageCode).Column("LANGUAGE_CODE").Not.Nullable().Length(5);
            Map(x => x.MbrCurrency).Column("MBR_CURRENCY").Not.Nullable().Precision(3);
            Map(x => x.InstallationDate).Column("INSTALLATION_DATE").CustomType<**SqlNumberDate**>().Precision(8);
            Cache.ReadWrite();
        }
    }
```
There is an issue with "custom type" that is still stands in my opinion.

**Comment by gokhanabatay** [comment]
@fredericDelaporte 
@hazzik 
I could pass this with option of OData so it does not create nullable expression.

HandleNullPropagation = HandleNullPropagationOption.False

May be it' ok that NHibernate does not support this kind of expression.
```c#
            var failureRetrieve = ISession.Query<MemberDefinition>().OrderBy(x => x.InstallationDate == null ? null : x.InstallationDate).ToList();
```

**Comment by fredericDelaporte** [comment]
No, it has to support it.

But you have to understand that investigating issues take considerable time to contributors, so please do yourself the effort of writing down a test case in NHibernate.Test.

**Comment by gokhanabatay** [comment]
You are right @fredericDelaporte but i cannot run NHibernate.Test in my local environment yet.
Next time I will reproduce issue before post to community.
Will you open the issue again?

**Comment by fredericDelaporte** [comment]
All the required tools are available for free (for some of them like VS2017 Community, provided they are used solely for contributing to free open source projects).

But there is also an alternate way: you can write your test case into a small test project like the one provided [here](http://nhibernate.info/blog/2008/10/03/the-best-way-to-solve-nhibernate-bugs-submit-good-unit-test.html) (of course, if you use it, update the NHibernate reference).

**Comment by fredericDelaporte** [comment]
I have put an updated version of the small test project: nhibernate/nhibernate-core-testcase#2.

**Comment by gokhanabatay** [comment]
@fredericDelaporte  I could not run your sample so, I create a small test project one entity and 6 test cases that simulate this and conditional filter sample please check it out.

Configuration: Postgresql, Log4net, FluentNhibernate, No Second Level Cache
Same issue happens  Postgressql too. 

https://github.com/gokhanabatay/NHibernateBugTest

**Comment by gokhanabatay** [comment]
> 
By the way, your "order by" is a bit strange, .OrderBy(x => x.InstallationDate) should result in the same ordering.
> 

I agree with you, but we are using OData with NHibernate and OData ApplyTo method generates that strange expression.  

```c#
 public static IQueryable ToODataQueryable<TEntity>(this IQueryable<TEntity> query, ODataQueryOptions<TEntity> oDataQueryOptions)
        {

            return oDataQueryOptions.ApplyTo(query) ;
        }
```
And they also have a parameter to disable this behaviour.

```c#HandleNullPropagation = HandleNullPropagationOption.False```

Thanks.
