### ISSUE TITLE
ISession.Get may fail with a null exception

### ISSUE THREAD

**Issue by RogerKratz** [nhibernate/nhibernate-core#1920]
`ISession.Get` fails with an "`InvalidOperationException` : Nullable object must have a value" when the entity class has batch lazy-loads enabled and at least one but less than `batch-size` other instances of the entity class are proxies awaiting loading.
(The get has to be done on an entity not yet loaded, even as an uninitialized proxy.)

Initial report:
---

Regression bug for 5.2.

We have a bunch of tests that after upgrade to 5.2 fails with stack trace below. Tried to figure out what/when this occur but no success yet. I guess there are some particular mapping that causes this? 
It happens both in tests when Get as well as Merge is called. 

The commit when this was added was 09120c02b3816f92d154e4c5b0e47daa0171eb16. 

I've tried to isolate this problem to a small test but haven't really found out what causes this. ping @maca88 - do you have a guess when this could happen?

```
System.InvalidOperationException : Nullable object must have a value.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at NHibernate.Engine.BatchFetchQueue.<GetEntityBatch>g__CheckCacheAndProcessResult|25_0(<>c__DisplayClass25_0& )
   at NHibernate.Engine.BatchFetchQueue.GetEntityBatch(IEntityPersister persister, Object id, Int32 batchSize, Boolean checkCache)
   at NHibernate.Loader.Entity.BatchingEntityLoader.Load(Object id, Object optionalObject, ISessionImplementor session)
   at NHibernate.Persister.Entity.AbstractEntityPersister.Load(Object id, Object optionalObject, LockMode lockMode, ISessionImplementor session)
   at NHibernate.Event.Default.DefaultLoadEventListener.LoadFromDatasource(LoadEvent event, IEntityPersister persister, EntityKey keyToLoad, LoadType options)
   at NHibernate.Event.Default.DefaultLoadEventListener.DoLoad(LoadEvent event, IEntityPersister persister, EntityKey keyToLoad, LoadType options)
   at NHibernate.Event.Default.DefaultLoadEventListener.Load(LoadEvent event, IEntityPersister persister, EntityKey keyToLoad, LoadType options)
   at NHibernate.Event.Default.DefaultLoadEventListener.ProxyOrLoad(LoadEvent event, IEntityPersister persister, EntityKey keyToLoad, LoadType options)
   at NHibernate.Event.Default.DefaultLoadEventListener.OnLoad(LoadEvent event, LoadType loadType)
   at NHibernate.Impl.SessionImpl.FireLoad(LoadEvent event, LoadType loadType)
   at NHibernate.Impl.SessionImpl.InternalLoad(String entityName, Object id, Boolean eager, Boolean isNullable)
   at NHibernate.Type.EntityType.ResolveIdentifier(Object id, ISessionImplementor session)
   at NHibernate.Type.EntityType.Replace(Object original, Object target, ISessionImplementor session, Object owner, IDictionary copyCache)
   at NHibernate.Type.CollectionType.ReplaceElements(Object original, Object target, Object owner, IDictionary copyCache, ISessionImplementor session)
   at NHibernate.Type.CollectionType.Replace(Object original, Object target, ISessionImplementor session, Object owner, IDictionary copyCache)
   at NHibernate.Type.TypeHelper.Replace(Object[] original, Object[] target, IType[] types, ISessionImplementor session, Object owner, IDictionary copiedAlready)
   at NHibernate.Event.Default.DefaultMergeEventListener.CopyValues(IEntityPersister persister, Object entity, Object target, ISessionImplementor source, IDictionary copyCache)
   at NHibernate.Event.Default.DefaultMergeEventListener.EntityIsDetached(MergeEvent event, IDictionary copyCache)
   at NHibernate.Event.Default.DefaultMergeEventListener.OnMerge(MergeEvent event, IDictionary copiedAlready)
   at NHibernate.Impl.SessionImpl.FireMerge(IDictionary copiedAlready, MergeEvent event)
   at NHibernate.Impl.SessionImpl.Merge(String entityName, Object obj, IDictionary copiedAlready)
   at NHibernate.Engine.CascadingAction.MergeCascadingAction.Cascade(IEventSource session, Object child, String entityName, Object anything, Boolean isCascadeDeleteEnabled)
   at NHibernate.Engine.Cascade.CascadeToOne(Object parent, Object child, IType type, CascadeStyle style, Object anything, Boolean isCascadeDeleteEnabled)
   at NHibernate.Engine.Cascade.CascadeCollectionElements(Object parent, Object child, CollectionType collectionType, CascadeStyle style, IType elemType, Object anything, Boolean isCascadeDeleteEnabled)
   at NHibernate.Engine.Cascade.CascadeCollection(Object parent, Object child, CascadeStyle style, Object anything, CollectionType type)
   at NHibernate.Engine.Cascade.CascadeAssociation(Object parent, Object child, IType type, CascadeStyle style, Object anything, Boolean isCascadeDeleteEnabled)
   at NHibernate.Engine.Cascade.CascadeOn(IEntityPersister persister, Object parent, Object anything)
   at NHibernate.Event.Default.DefaultMergeEventListener.CascadeOnMerge(IEventSource source, IEntityPersister persister, Object entity, IDictionary copyCache)
   at NHibernate.Event.Default.DefaultMergeEventListener.EntityIsDetached(MergeEvent event, IDictionary copyCache)
   at NHibernate.Event.Default.DefaultMergeEventListener.OnMerge(MergeEvent event, IDictionary copiedAlready)
   at NHibernate.Impl.SessionImpl.FireMerge(IDictionary copiedAlready, MergeEvent event)
   at NHibernate.Impl.SessionImpl.Merge(String entityName, Object obj, IDictionary copiedAlready)
   at NHibernate.Engine.CascadingAction.MergeCascadingAction.Cascade(IEventSource session, Object child, String entityName, Object anything, Boolean isCascadeDeleteEnabled)
   at NHibernate.Engine.Cascade.CascadeToOne(Object parent, Object child, IType type, CascadeStyle style, Object anything, Boolean isCascadeDeleteEnabled)
   at NHibernate.Engine.Cascade.CascadeCollectionElements(Object parent, Object child, CollectionType collectionType, CascadeStyle style, IType elemType, Object anything, Boolean isCascadeDeleteEnabled)
   at NHibernate.Engine.Cascade.CascadeCollection(Object parent, Object child, CascadeStyle style, Object anything, CollectionType type)
   at NHibernate.Engine.Cascade.CascadeAssociation(Object parent, Object child, IType type, CascadeStyle style, Object anything, Boolean isCascadeDeleteEnabled)
   at NHibernate.Engine.Cascade.CascadeOn(IEntityPersister persister, Object parent, Object anything)
   at NHibernate.Event.Default.DefaultMergeEventListener.CascadeOnMerge(IEventSource source, IEntityPersister persister, Object entity, IDictionary copyCache)
   at NHibernate.Event.Default.DefaultMergeEventListener.EntityIsDetached(MergeEvent event, IDictionary copyCache)
   at NHibernate.Event.Default.DefaultMergeEventListener.OnMerge(MergeEvent event, IDictionary copiedAlready)
   at NHibernate.Event.Default.DefaultMergeEventListener.OnMerge(MergeEvent event)
   at NHibernate.Impl.SessionImpl.FireMerge(MergeEvent event)
   at NHibernate.Impl.SessionImpl.Merge(String entityName, Object obj)
   at NHibernate.Impl.SessionImpl.Merge[T](T entity)
```

**Comment by fredericDelaporte** [comment]
If you could run your tests with the pdb from the symbol package, it should then add which line of code has failed, which may help.

The symbol package is published on https://nuget.smbsrc.net, but currently it has a certificate trouble...
PDBs are also available in the SourceForge release (https://sourceforge.net/projects/nhibernate/files/NHibernate/5.2.0/, bin package) or directly in the TeamCity build artifacts (for v5.2.0, [here](https://teamcity.jetbrains.com/viewLog.html?buildId=1799196&buildTypeId=NHibernate_NHibernateReleasePackage&tab=artifacts&branch_NHibernate=%3Cdefault%3E)).

**Comment by fredericDelaporte** [comment]
So it seems that `idIndex` can be null here:

https://github.com/nhibernate/nhibernate-core/blob/fdac0d05db7b0f530848daec0a988924743e54f2/src/NHibernate/Engine/BatchFetchQueue.cs#L458

This code is fairly complex, but as I read it, this may happen if there is less than `batchsize` entities with pending load and the entity to be loaded was not awaiting its load. It looks like this last condition "the entity to be loaded was not awaiting its load" is not expected by the code.

If it is an overlooked case, this code here needs to evolve to support that case.

Otherwise, if that is not supposed to ever happen, there is a bug somewhere else, occurring before this code gets executed.

@maca88, do you remember if it is possible for the batch loader to have to load an entity which was not registered for batch loading?

**Comment by RogerKratz** [comment]
@fredericDelaporte 
Ah, batchsize - good guess! In our failing tests, there was an entity involved with "batch-size=x" set on its <class>, when temporarily remove that, our tests went green.

I wont be in front of a computer more today but if you want to, I can (hopefully) create a failing PR tomorrow.

This was a nasty one. Thanks for your help so far.

**Comment by fredericDelaporte** [comment]
Yes, a failing PR is always a great help, thanks.

**Comment by maca88** [comment]
> do you remember if it is possible for the batch loader to have to load an entity which was not registered for batch loading?

In all tests that I did, this never happened.

> do you have a guess when this could happen?

After some debugging I am able to reproduce the problem with live debugging, here are the steps:
1. Add breakpoints [here](https://github.com/nhibernate/nhibernate-core/blob/fdac0d05db7b0f530848daec0a988924743e54f2/src/NHibernate/Engine/BatchFetchQueue.cs#L458) and [here](https://github.com/nhibernate/nhibernate-core/blob/fdac0d05db7b0f530848daec0a988924743e54f2/src/NHibernate/Engine/BatchFetchQueue.cs#L411)
2. Debug the test [BatchableCacheFixture.MultipleGetReadOnlyTest](https://github.com/nhibernate/nhibernate-core/blob/fdac0d05db7b0f530848daec0a988924743e54f2/src/NHibernate.Test/CacheTest/BatchableCacheFixture.cs#L205)
3. When the code stops at the first breakpoint go to the stacktrace window and double click on the row with name (should be fifth row from top to bottom):
```
 	NHibernate.dll!NHibernate.Event.Default.DefaultLoadEventListener.ReturnNarrowedProxy(NHibernate.Event.LoadEvent event, NHibernate.Persister.Entity.IEntityPersister persister, NHibernate.Engine.EntityKey keyToLoad, NHibernate.Event.LoadType options, NHibernate.Engine.IPersistenceContext persistenceContext, object proxy) Line 189	C#

```
4. Wait for VS to load the variables in that region, then click back on the first row in the stacktrace window and hit F5 (continue)
5. Now the code should stop at the second breakpoint and the `idIndex` will not have the value set

There must be something (like a custom listener) that triggers the removal of the loadable entity keys which happens between `AddBatchLoadableEntityKey` and `GetEntityBatch` calls. 
The solution is probably to modify the `GetEntityBatch` and `GetCollectionBatch` to support this scenario.

**Comment by RogerKratz** [comment]
@maca88 As stated above, this happened to me when having "batch-size" set on the class mapping, if that helps you.

Hopefully I can write a failing test tomorrow (not in front of a computer atm).

**Comment by RogerKratz** [comment]
@maca88 @fredericDelaporte 
Failing test here, https://github.com/nhibernate/nhibernate-core/pull/1924.

I tried to apply a fix as well but current impl is quite (too?) complex so I gave it up quickly and left that part to you who knows this code base better than me... Please tell me if you want me to continue to find a fix for this issue.

**Comment by fredericDelaporte** [comment]
I agree this implementation is a bit too complex in my opinion. Note it has not been introduced by 09120c0, it was already there previously. 09120c0 has refactored it though.

**Comment by fredericDelaporte** [comment]
I have updated the title and description for more closely describe the actual issue.

**Comment by fredericDelaporte** [comment]
I have set a due date for 5.2.1 to the start of January. But this regression here is likely to impact a lot of users. Should we release 5.2.1 sooner?

**Comment by RogerKratz** [comment]
Thanks for the fix! 
About release date... Personally I would highly appreciate a release ASAP.

**Comment by hazzik** [comment]
I agree with @RogerKratz
