### ISSUE TITLE
.NET Core 3 - BadImageFormatException: Bad IL format

### ISSUE THREAD

**Issue by jaryn-kubik** [nhibernate/nhibernate-core#2228]
Is NHibernate 5.2.6 supposed to work with .NET Core 3?
I tried upgrading our work project to .NET Core 3 and I'm getting this exception when working with any table that has navigation properties:
```
NHibernate.Exceptions.GenericADOException: could not execute query
[ SELECT this_.id_lk as id1_77_0_, this_.id_typ as id2_77_0_, this_.data as data3_77_0_ FROM dba.KartyL_ExtInfo this_ WHERE this_.id_typ = ? and this_.id_lk = ? ]
  Name:cp0 - Value:WKChecksAfterLogin  Name:cp1 - Value:1
[SQL: SELECT this_.id_lk as id1_77_0_, this_.id_typ as id2_77_0_, this_.data as data3_77_0_ FROM dba.KartyL_ExtInfo this_ WHERE this_.id_typ = ? and this_.id_lk = ?]
 ---> System.BadImageFormatException: Bad IL format.
   at ClientRegisterProxy.get_HibernateLazyInitializer()
   at NHibernate.Event.Default.DefaultLoadEventListener.CreateProxyIfNecessary(LoadEvent event, IEntityPersister persister, EntityKey keyToLoad, LoadType options, IPersistenceContext persistenceContext)
   at NHibernate.Event.Default.DefaultLoadEventListener.ProxyOrLoad(LoadEvent event, IEntityPersister persister, EntityKey keyToLoad, LoadType options)
   at NHibernate.Event.Default.DefaultLoadEventListener.OnLoad(LoadEvent event, LoadType loadType)
   at NHibernate.Impl.SessionImpl.FireLoad(LoadEvent event, LoadType loadType)
   at NHibernate.Impl.SessionImpl.InternalLoad(String entityName, Object id, Boolean eager, Boolean isNullable)
   at NHibernate.Type.EntityType.ResolveIdentifier(Object id, ISessionImplementor session)
   at NHibernate.Type.EntityType.ResolveIdentifier(Object value, ISessionImplementor session, Object owner)
   at NHibernate.Engine.TwoPhaseLoad.InitializeEntity(Object entity, Boolean readOnly, ISessionImplementor session, PreLoadEvent preLoadEvent, PostLoadEvent postLoadEvent, Action`2 cacheBatchingHandler)
   at NHibernate.Loader.Loader.InitializeEntitiesAndCollections(IList hydratedObjects, DbDataReader reader, ISessionImplementor session, Boolean readOnly, CacheBatcher cacheBatcher)
   at NHibernate.Loader.Loader.DoQuery(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.DoQueryAndInitializeNonLazyCollections(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.DoList(ISessionImplementor session, QueryParameters queryParameters, IResultTransformer forcedResultTransformer)
   --- End of inner exception stack trace ---
   at NHibernate.Loader.Loader.DoList(ISessionImplementor session, QueryParameters queryParameters, IResultTransformer forcedResultTransformer)
   at NHibernate.Impl.SessionImpl.List(CriteriaImpl criteria, IList results)
   at NHibernate.Impl.CriteriaImpl.List(IList results)
   at NHibernate.Impl.CriteriaImpl.List[T]()
   at NHibernate.Criterion.QueryOver`1.List()
   at NHibernate.Criterion.QueryOver`1.NHibernate.IQueryOver<TRoot>.List()
```
Usually BadImageFormatException means some 32/64bit mixing, but I've tried forcing x86 or x64 instead of using AnyCPU with no effect.

**Comment by bahusoid** [comment]
I wonder if it's related to https://github.com/nhibernate/nhibernate-core/issues/2085

**Comment by jaryn-kubik** [comment]
Nevermind, we had ProxyValidator turned off. When we turned it on, we found out that some properties/methods in our entities weren't marked as virtual. When we fixed that, it started working.
Still a bit weird that it worked fine on net472.

**Comment by hazzik** [comment]
Good. Thanks for the update.

**Comment by mihadeth** [comment]
@jaryn-kubik Having a similar problem. Can you please share how exactly you enable ProxyValidator? I'm failing to find any useful information. Thank you

**Comment by fredericDelaporte** [comment]
[`use_proxy_validator`](https://nhibernate.info/doc/nhibernate-reference/session-configuration.html#configuration-optional)
