### ISSUE TITLE
System.Type.GetType in Logging.log4net can crash, making configuration fail

### ISSUE THREAD

**Issue by tb2johm** [nhibernate/nhibernate-core#2342]
So I noticed this when I loaded my DLL in another program than I usually do. What happened was that NHibernate crashed upon configuration (I used `var config = new NHibernate.Cfg.Configuration();`). I found it to have something to do with log4net, and adding log4net to the execution folder fixed the problem, but I had never used it before so I didn't understand why I needed to use it now.

Doing some investigation I found out that the crash occurs at the `GetType` statement [here](https://github.com/nhibernate/nhibernate-core/blob/master/src/NHibernate/Logging.log4net.cs#L44). So turns out that the `GetType` can throw an exception, this might be due to some kind of programming error in the other application that I used. But I still don't think it should crash NHibernate.

### Suggestion:
It would be very easy just to replace that same line with the following code
```
System.Type type;
try
{
    type = System.Type.GetType(typeName);
}
catch (Exception)
{
    type = null;
}
```

**Comment by bahusoid** [comment]
Please provide more details:  full exception stack trace and target framework ( .net core or full .net framework?).

**Comment by tb2johm** [comment]
So this is for .net.

Exception message:
_Could not load file or assembly 'log4net' or one of its dependencies. An argument was out of its legal range. (Exception from HRESULT: 0x80131502)_

This is the full stack trace:
```
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   at System.Type.GetType(String typeName)
   at NHibernate.Log4NetLoggerFactory.GetLogManagerType() in C:\Markus\others\nhibernate-core\src\NHibernate\Logging.log4net.cs:line 47
```
This exception has an inner exception which also has a stack trace (I can't provide it in full because it will give information that is secret, however the first line shows how it comes in to the program that is calling the dll in the first place):
```
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
```
So the exception really is from the calling application (so probably this will only happen if there is an error in the application using NHibernate, but - as I said - I don't think that NHibernate should crash anyways.

**Comment by bahusoid** [comment]
Yeah as I suspected it's from user custom assembly resolution code... I personally don't like introducing any exceptions handling to fix user errors. But let's see what other members think.

And how logging is configured in your app? In 5.3 this type resolution is skipped if user provided some other logging configuration (for instance via `NHibernateLogger.SetLoggersFactory` call)

**Comment by tb2johm** [comment]
I don't use any NHibernate logging. So I'm expecting it to choose the `NoLoggingNHibernateLoggerFactory`.

**Comment by maca88** [comment]
As log4net is an optional dependency that we check, I think that we should not throw an exception inside NHibernate and let the exception be thrown when the user tries to configure the logger by using `log4net.Config.XmlConfigurator` in his assembly.

**Comment by bahusoid** [comment]
>  and let the exception be thrown when the user tries to configure the logger by using log4net.Config.XmlConfigurator in his assembly.

I don't get this part -  log4net is not used at all in this scenario.

>  I think that we should not throw an exception inside NHibernate

Well OK. But we need to make sure if user explicitly wants to use log4net - we still need to throw. 

@tb2johm Just FYI in 5.3 (not yet released) this issue can also be omitted if you explicitly call `NHibernateLogger.SetLoggersFactory(null)` somewhere before  `Configuration` class is used.

**Comment by maca88** [comment]
> I don't get this part - log4net is not used at all in this scenario.

That part was for users that explicitly wants to use log4net.

> But we need to make sure if user explicitly wants to use log4net - we still need to throw.

IMO there is no need to throw inside NHibernate as the exception will be thrown anyways, when the user will try to configure log4net. In order to be more clear I made the following console application:
```c#
class Program
{
    static void Main(string[] args)
    {
        Initialize();
        WithoutLog4net();
        WithLog4net();
    }

    private static void WithoutLog4net()
    {
        Console.WriteLine("WithoutLog4et - GetLogManagerType...");
        var type = GetLogManagerType();
    }

    private static void WithLog4net()
    {
        Console.WriteLine("WithLog4net - GetLogManagerType...");
        var type = GetLogManagerType();
        ConfigureLog4net();
    }

    private static void ConfigureLog4net()
    {
        Console.WriteLine("Configuring log4net...");
        var repo = log4net.LogManager.CreateRepository("test");
        log4net.Config.XmlConfigurator.Configure(repo);
    }

    private static Type GetLogManagerType()
    {
        try
        {
            return Type.GetType("Log4net.LogManager, Log4net");
        }
        catch
        {
            return null;
        }
    }

    private static void Initialize()
    {
        AppDomain.CurrentDomain.AssemblyResolve += CurrentDomainOnAssemblyResolve;
    }

    private static Assembly CurrentDomainOnAssemblyResolve(object sender, ResolveEventArgs args)
    {
        throw new InvalidOperationException();
    }
}
```
if the above console application is started without having log4net.dll in the "bin" folder, the following input will be printed in the console:
```
WithoutLog4et - GetLogManagerType...
WithLog4net - GetLogManagerType...

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'log4net, Version=2.0.8.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a' or one of its dependencies. An operation is not legal in the current state. (Exception from HRESULT: 0x80131509) ---> System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at ConsoleApp.Program.CurrentDomainOnAssemblyResolve(Object sender, ResolveEventArgs args) in  \ConsoleApp\Program.cs:line 54
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
   --- End of inner exception stack trace ---
   at ConsoleApp.Program.ConfigureLog4net()
   at ConsoleApp.Program.WithLog4net() in \ConsoleApp\Program.cs:line 25
   at ConsoleApp.Program.Main(String[] args) in \ConsoleApp\Program.cs:line 12
PS \ConsoleApp\bin\Debug>
```
So my point is that even when `GetLogManagerType` method never throws, the application will still throw an exception when trying to call `ConfigureLog4net` method.

**Comment by fredericDelaporte** [comment]
I agree with @maca88.
