### ISSUE TITLE
Unable to cast object of type 'NHibernate.Cache.CacheKey' to type 'NHibernate.Cache.QueryKey'.

### ISSUE THREAD

**Issue by javvids** [nhibernate/nhibernate-core#2410]
We get following error frequently since we moved from Syscache2 to CorememoryCache

```
System.InvalidCastException: Unable to cast object of type 'NHibernate.Cache.CacheKey' to type 'NHibernate.Cache.QueryKey'.
   at NHibernate.Cache.QueryKey.Equals(Object other)
   at System.Collections.Generic.ObjectEqualityComparer`1.Equals(T x, T y)
   at System.Collections.Generic.ObjectEqualityComparer`1.Equals(T x, T y)
   at System.Collections.Concurrent.ConcurrentDictionary`2.TryGetValue(TKey key, TValue& value)
   at Microsoft.Extensions.Caching.Memory.MemoryCache.TryGetValue(Object key, Object& result)
   at NHibernate.Caches.CoreMemoryCache.CoreMemoryCacheBase.Get(Object key)
   at NHibernate.Cache.CacheBase.GetMany(Object[] keys)
   at NHibernate.Cache.ReadWriteCache.PutMany(CacheKey[] keys, Object[] values, Int64 timestamp, Object[] versions, IComparer[] versionComparers, Boolean[] minimalPuts)
   at NHibernate.Cache.CachePutBatch.Execute(CachePutData[] data)
   at NHibernate.Cache.CacheBatcher.ExecuteBatch()
   at NHibernate.Loader.Loader.InitializeEntitiesAndCollections(IList hydratedObjects, DbDataReader reader, ISessionImplementor session, Boolean readOnly, CacheBatcher cacheBatcher)
   at NHibernate.Loader.Loader.DoQuery(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.DoQueryAndInitializeNonLazyCollections(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.DoList(ISessionImplementor session, QueryParameters queryParameters, IResultTransformer forcedResultTransformer)
   --- End of inner exception stack trace ---
   at NHibernate.Loader.Loader.DoList(ISessionImplementor session, QueryParameters queryParameters, IResultTransformer forcedResultTransformer)
   at NHibernate.Impl.SessionImpl.List(CriteriaImpl criteria, IList results)
   at NHibernate.Impl.CriteriaImpl.List(IList results)
   at NHibernate.Impl.CriteriaImpl.List[T]()
```

**Comment by fredericDelaporte** [comment]
Most caches do use the key object string representation as the actual cache key, but it appears it is not the case of `CoreMemoryCache`. Moreover, a defect in the `QueryKey` implementation causes it to fail being directly compared to another kind of key like `CacheKey`.

This defect will be fixed in NHibernate, so your issue has been transferred here.
Rather than waiting for the release fix, you may also work around this bug by using the [`RtMemoryCache`](https://www.nuget.org/packages/NHibernate.Caches.RtMemoryCache/), which uses the string representation of the key instead of the key, and so does not suffer from this bug.

(This other memory cache is available for .Net Core too since its v5.4.0 version.)
