### ISSUE TITLE
Asp.Net - .Net Core -  MVC - Nhibernate add/update issue after adding a new column on SQL SERVER

### ISSUE THREAD

**Issue by katarukoti** [nhibernate/nhibernate-core#2434]
Please help me with the below issue.

I have added a new column to Existing Table and Rebuild the code and It works fine when reading a record

The below Read/Get Method is able to pull the Records from the Database.
```c#
public TEntity Get(int id) {      
  Session.CacheMode = CacheMode.Normal;
  var entity = Session.Get<TEntity>(id);
  return entity;
}
```

While making any changes and try to save it gives me the exception (Below is the method which is invoking at the time of Update)
```c#
public bool Update(TEntity entity)
{
   Session.Transaction.Begin();
   Session.SaveOrUpdate(entity);
   Session.Flush();
   Session.Transaction.Commit(); (Exception at this line)
   return true;
}
```

Exception Details:
```
Message: could not execute batch command.[SQL: SQL not available]
Inner Exception: {"Invalid column name 'UseTerms'."}    
Stack Trace:
at NHibernate.Engine.ActionQueue.BeforeTransactionCompletionProcessQueue.BeforeTransactionCompletion()
   at NHibernate.Impl.SessionImpl.BeforeTransactionCompletion(ITransaction tx)
   at NHibernate.Transaction.AdoTransaction.Commit()
   at WebApp.Core.Data.NHibernateData.Repositories.NHibernateRepository`1.Update(TEntity entity) in D:\WebApp\Core\WebApp.Core.Data.NHibernateData\Repositories\NHibernateRepository.cs:line 55
   at WebApp.Core.Logic.Configuration.GroupConfigurationLogic.SaveGroupConig[TEntity,TDto](Int32 groupId, IRepository`1 repository, TDto dto) in D:\WebApp\Core\WebApp.Core.Logic\Configuration\GroupConfigurationLogic.cs:line 63
   at WebApp.Core.Logic.Configuration.ConfigurationService.SaveGroupConfiguration(GroupConfigurationDto groupConfiguration, Guid updatedBy) in D:\WebApp\Core\WebApp.Core.Logic\Configuration\ConfigurationService.cs:line 91
   at WebApp.Core.Wcf.ConfigurationService.SaveGroupConfiguration(GroupConfigurationDto groupConfiguration, Guid updatedBy) in D:\WebApp\Core\WebApp.Core.Wcf\ConfigurationService.svc.cs:line 24
   at SyncInvokeSaveGroupConfiguration(Object , Object[] , Object[] )
   at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
   at System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc& rpc)
```
![Capture](https://user-images.githubusercontent.com/12154728/87856910-fba15b80-c93f-11ea-9126-98f232ea6a9c.PNG)

**Comment by fredericDelaporte** [comment]
Hello, you have reached the issue tracker, meant for bug reports or feature requests.

Please post on the [nhusers group](https://groups.google.com/forum/#!forum/nhusers) for support requests (or see [Groups](https://nhibernate.info/groups.html)).
