### ISSUE TITLE
Lazy loading swallows actual errors.

### ISSUE THREAD

**Issue by fairking** [nhibernate/nhibernate-core#2470]
NH v. 5.3.1.

I had the following error on loading a collection (eg. `invoice.Items.ToList()`):
```
  {"illegal access to loading collection"}
    Data: {System.Collections.ListDictionaryInternal}
    EntityId: null
    EntityName: null
    HResult: -2146233088
    HelpLink: null
    InnerException: null
    Message: "illegal access to loading collection"
    Source: "NHibernate"
    StackTrace: "   at NHibernate.Collection.AbstractPersistentCollection.Initialize(Boolean writing)\r\n   at NHibernate.Collection.AbstractPersistentCollection.Read()\r\n   at NHibernate.Collection.AbstractPersistentCollection.ReadSize()\r\n   at NHibernate.Collection.Generic.PersistentGenericSet`1.get_Count()\r\n   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)\r\n   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)\r\n 
    TargetSite: {Void Initialize(Boolean)}
```
But after I tried to load those items via query (eg. `session.Query<InvoiceItem>().ToList()`) I encountered the actual error which was:
```
{"Can't Parse None as ObservationTypeEnum"}
    Data: {System.Collections.ListDictionaryInternal}
    HResult: -2146233088
    HelpLink: null
    InnerException: {"Requested value 'None' was not found."}
    Message: "Can't Parse None as ObservationTypeEnum"
    Source: "NHibernate"
    StackTrace: "   at NHibernate.Type.EnumStringType.GetInstance(Object code)\r\n   at NHibernate.Type.EnumStringType.Get(DbDataReader rs, Int32 index, ISessionImplementor session)\r\n   at NHibernate.Type.NullableType.NullSafeGet(DbDataReader rs, String name, ISessionImplementor session)\r\n   at NHibernate.Type.NullableType.NullSafeGet(DbDataReader rs, String[] names, ISessionImplementor session, Object owner)\r\n   at NHibernate.Type.NullableType.NullSafeGetAsync(DbDataReader rs, String[] names, ISessionImplementor session, Object owner, CancellationToken cancellationToken)\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at NHibernate.Persister.Entity.AbstractEntityPersister.<HydrateAsync>d__12.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServic
es.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()\r\n   at NHibernate.Loader.Loader.<LoadFromResultSetAsync>d__18.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()\r\n   at NHibernate.Loader.Loader.<InstanceNotYetLoadedAsync>d__15.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at NHibernate.Loader.Loader.<GetRowAsync>d__13.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.Thr
owForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at NHibernate.Loader.Loader.<GetRowFromResultSetAsync>d__3.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at NHibernate.Loader.Loader.<DoQueryAsync>d__5.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()\r\n   at NHibernate.Loader.Loader.<DoQueryAndInitializeNonLazyCollectionsAsync>d__1.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(
Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()\r\n   at NHibernate.Loader.Loader.<DoListAsync>d__38.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()\r\n   at NHibernate.Loader.Loader.<ListIgnoreQueryCacheAsync>d__32.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at NHibernate.Hql.Ast.ANTLR.QueryTranslato
rImpl.<ListAsync>d__0.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at NHibernate.Engine.Query.HQLQueryPlan.<PerformListAsync>d__0.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()\r\n   at NHibernate.Impl.SessionImpl.<ListAsync>d__17.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at NHibernate.Impl.SessionImpl.<ListAsync>d__17.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.T
askAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()\r\n   at NHibernate.Impl.AbstractSessionImpl.<ListAsync>d__5`1.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()\r\n   at NHibernate.Impl.AbstractQueryImpl2.<ListAsync>d__5`1.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult
()\r\n   at NHibernate.Linq.DefaultQueryProvider.<ExecuteListAsync>d__0`1.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()\r\n   at NHibernate.Linq.LinqExtensionMethods.<>c__DisplayClass59_0`1.<<ToListAsync>g__InternalToListAsync|0>d.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n
    TargetSite: {System.Object GetInstance(System.Object)}
```

After fixing the issue the "illegal access" error dissapeared.

**Please add the actual error of loading objects into the INNER exception of "illegal access" error.**

Thanks.

**Comment by fairking** [comment]
There are dozens questions on stackoverflow with this confusing error. Many people are confused with the error message:
https://stackoverflow.com/search?q=illegal+access+to+loading+collection

**Comment by fredericDelaporte** [comment]
There is no obvious swallowing catch in the code to fix. There is no catch at all where the first exception is thrown, so there is no exception to put as an inner exception either.

To actually fix your case, which may or may not be the same than those found on StackOverflow, may you please provide a test case?

**Comment by fairking** [comment]
Thanks @fredericDelaporte for your response. After I fixed the enum problem the lazy loading error went away. I solved my issue. I was thinking we can improve the lazy loading error to put more details as I can see people have many similar errors on stackoverflow. Please feel free to close the ticket if you think it is no possible to do. Cheers.

**Comment by fredericDelaporte** [comment]
It should be possible to do, but for this we need a way to reproduce the trouble. Can you please provide us with a test case?

**Comment by bahusoid** [comment]
Can't reproduce. For me it gives:
```C#
NHibernate.Test.NHSpecificTest.GH2470.ByCodeFixture.CollectionInitializationSwallowsRealException

NHibernate.HibernateException : Can't Parse None as MyEnum
  ----> System.ArgumentException : Requested value 'None' was not found.
   at NHibernate.Type.EnumStringType.GetInstance(Object code)
   at NHibernate.Type.NullableType.NullSafeGet(DbDataReader rs, String name, ISessionImplementor session)
   at NHibernate.Persister.Entity.AbstractEntityPersister.Hydrate(DbDataReader rs, Object id, Object obj, String[][] suffixedPropertyColumns, ISet`1 fetchedLazyProperties, Boolean allProperties, Int32[] indexes, ISessionImplementor session)
   at NHibernate.Persister.Entity.LoadableExtensions.Hydrate(ILoadable loadable, DbDataReader rs, Object id, Object obj, String[][] suffixedPropertyColumns, ISet`1 fetchedLazyProperties, Boolean allProperties, ISessionImplementor session)
   at NHibernate.Loader.Loader.LoadFromResultSet(DbDataReader rs, Int32 i, Object obj, ILoadable persister, EntityKey key, LockMode lockMode, ILoadable rootPersister, ISessionImplementor session)
   at NHibernate.Loader.Loader.InstanceNotYetLoaded(DbDataReader dr, Int32 i, ILoadable persister, EntityKey key, LockMode lockMode, EntityKey optionalObjectKey, Object optionalObject, IList hydratedObjects, ISessionImplementor session)
   at NHibernate.Loader.Loader.GetRow(DbDataReader rs, ILoadable[] persisters, EntityKey[] keys, Object optionalObject, EntityKey optionalObjectKey, LockMode[] lockModes, IList hydratedObjects, ISessionImplementor session, Boolean mustLoadMissingEntity, Action`2 cacheBatchingHandler)
   at NHibernate.Loader.Loader.GetRowFromResultSet(DbDataReader resultSet, ISessionImplementor session, QueryParameters queryParameters, LockMode[] lockModeArray, EntityKey optionalObjectKey, IList hydratedObjects, EntityKey[] keys, Boolean returnProxies, IResultTransformer forcedResultTransformer, QueryCacheResultBuilder queryCacheResultBuilder, Action`2 cacheBatchingHandler)
   at NHibernate.Loader.Loader.DoQuery(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer, QueryCacheResultBuilder queryCacheResultBuilder)
   at NHibernate.Loader.Loader.DoQueryAndInitializeNonLazyCollections(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer, QueryCacheResultBuilder queryCacheResultBuilder)
   at NHibernate.Loader.Loader.LoadCollection(ISessionImplementor session, Object id, IType type)
   at NHibernate.Event.Default.DefaultInitializeCollectionEventListener.OnInitializeCollection(InitializeCollectionEvent event)
   at NHibernate.Impl.SessionImpl.InitializeCollection(IPersistentCollection collection, Boolean writing)
   at NHibernate.Collection.AbstractPersistentCollection.Initialize(Boolean writing)
   at NHibernate.Collection.AbstractPersistentCollection.ReadSize()
   at NHibernate.Collection.Generic.PersistentGenericSet`1.get_Count()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```


Attaching solution:
[nhibernate-core-testcase.zip](https://github.com/nhibernate/nhibernate-core/files/5056422/nhibernate-core-testcase.zip)


So please provide reproducible example (see `CollectionInitializationSwallowsRealException` in attached solution)

**Comment by bahusoid** [comment]
How this invoice was loaded to session?

**Comment by bahusoid** [comment]
Actually I think I know what's going on. I think there is somewhere exception swallowing in **your** code. I can reproduce this exception with the following adjustment in my test:
```C#
try
{
	result.Children.ToList();
}
catch
{
	// second call would give "illegal access to loading collection"
	result.Children.ToList();
}
```

**Comment by fairking** [comment]
Ok, I could not reproduce the error too using the simple example bellow:
https://github.com/fairking/NhOdataTest/tree/2470_Lazy_loading_swallows_actual_errors

Please feel free to close the ticket. I will rise a new ticket if I find the actual cause of the problem.

Thanks guys.
