### ISSUE TITLE
Intentional or not, usage of IValidatable leads to not expected exceptions

### ISSUE THREAD

**Issue by dvdwouwe** [nhibernate/nhibernate-core#2505]
Hi,

At our company we are using IValidatable very heavily, this ensures that all data is ready to be written to the store is always validated. This works also for implicit tracked entities.
I'm trying to describe a scenario that give us a rather strange behavior:

We have 2 entiies (class A and class B), not related to each other. One of the entity has implemented the IValidatable interface:
The code below is in fact a test a written to see the current behavior

```
using System;
using NHibernate.Classic;

namespace NHibernate.Test.NHSpecificTest.GHxxxx
{
	public class A
	{
		public virtual Guid Id { get; set; }

		public virtual string Name { get; set; }
	}

	public class B : IValidatable
	{
		public virtual Guid Id { get; set; }

		public virtual int Value { get; set; }

		public virtual void Validate()
		{
			if (Value < 0)
			{
				throw new ValidationFailure();
			}
		}
	}
}
```

```
<?xml version="1.0" encoding="utf-8" ?>
<hibernate-mapping xmlns="urn:nhibernate-mapping-2.2" assembly="NHibernate.Test" namespace="NHibernate.Test.NHSpecificTest.GHxxxx">
  <class name="A">
    <id name="Id" generator="guid.comb"/>
    <property name="Name" />
  </class>
  <class name="B">
    <id name="Id" generator="guid.comb"/>
    <property name="Value"  />
  </class>
</hibernate-mapping>
```

Running following test is failing:
```
using System.Linq;
using NUnit.Framework;

namespace NHibernate.Test.NHSpecificTest.GHxxxx
{
	[TestFixture]
	public class Fixture : BugTestCase
	{
		protected override bool AppliesTo(Dialect.Dialect dialect)
		{
			return dialect.SupportsScalarSubSelects;
		}

		protected override void OnSetUp()
		{
			using (var session = OpenSession())
			using (var transaction = session.BeginTransaction())
			{
				session.Save(new A {Name = "test"});
				session.Save(new B {Value = 5});

				transaction.Commit();
			}
		}

		protected override void OnTearDown()
		{
			using (var session = OpenSession())
			using (var transaction = session.BeginTransaction())
			{
				session.Delete("from System.Object");
				transaction.Commit();
			}
		}

		[Test]
		public void CanNotQuery()
		{
			using (var session = OpenSession())
			using (var transaction = session.BeginTransaction())
			{
				var b = session.Query<B>().Single();
				b.Value = -1;
				var a = session.Query<A>().ToList();
				transaction.Commit();
			}
		}
	}
}
```

A a certain moment we are reshaping instance B, and it is not yet ready for going to be saved, but I need a query for instances of class A. The query leads to following stack trace:

> NHibernate.Classic.ValidationFailure : A validation failure occurred
   at NHibernate.Test.NHSpecificTest.GHxxxx.B.Validate() in C:\Development\GitHub\nhibernate-core\src\NHibernate.Test\NHSpecificTest\GHxxxx\Entity.cs:line 26
   at NHibernate.Event.Default.DefaultFlushEntityEventListener.Validate(Object entity, IEntityPersister persister, Status status) in C:\Development\GitHub\nhibernate-core\src\NHibernate\Event\Default\DefaultFlushEntityEventListener.cs:line 291
   at NHibernate.Event.Default.DefaultFlushEntityEventListener.ScheduleUpdate(FlushEntityEvent event) in C:\Development\GitHub\nhibernate-core\src\NHibernate\Event\Default\DefaultFlushEntityEventListener.cs:line 248
   at NHibernate.Event.Default.DefaultFlushEntityEventListener.OnFlushEntity(FlushEntityEvent event) in C:\Development\GitHub\nhibernate-core\src\NHibernate\Event\Default\DefaultFlushEntityEventListener.cs:line 44
   at NHibernate.Event.Default.AbstractFlushingEventListener.FlushEntities(FlushEvent event) in C:\Development\GitHub\nhibernate-core\src\NHibernate\Event\Default\AbstractFlushingEventListener.cs:line 163
   at NHibernate.Event.Default.AbstractFlushingEventListener.FlushEverythingToExecutions(FlushEvent event) in C:\Development\GitHub\nhibernate-core\src\NHibernate\Event\Default\AbstractFlushingEventListener.cs:line 61
   at NHibernate.Event.Default.DefaultAutoFlushEventListener.OnAutoFlush(AutoFlushEvent event) in C:\Development\GitHub\nhibernate-core\src\NHibernate\Event\Default\DefaultAutoFlushEventListener.cs:line 32
   at NHibernate.Impl.SessionImpl.AutoFlushIfRequired(ISet`1 querySpaces) in C:\Development\GitHub\nhibernate-core\src\NHibernate\Impl\SessionImpl.cs:line 1067
   at NHibernate.Impl.SessionImpl.List(IQueryExpression queryExpression, QueryParameters queryParameters, IList results, Object filterConnection) in C:\Development\GitHub\nhibernate-core\src\NHibernate\Impl\SessionImpl.cs:line 546
   at NHibernate.Impl.SessionImpl.List(IQueryExpression queryExpression, QueryParameters queryParameters, IList results) in C:\Development\GitHub\nhibernate-core\src\NHibernate\Impl\SessionImpl.cs:line 523
   at NHibernate.Impl.AbstractSessionImpl.List[T](IQueryExpression query, QueryParameters parameters) in C:\Development\GitHub\nhibernate-core\src\NHibernate\Impl\AbstractSessionImpl.cs:line 182
   at NHibernate.Impl.AbstractQueryImpl2.List[T]() in C:\Development\GitHub\nhibernate-core\src\NHibernate\Impl\AbstractQueryImpl2.cs:line 111
   at NHibernate.Linq.DefaultQueryProvider.ExecuteList[TResult](Expression expression) in C:\Development\GitHub\nhibernate-core\src\NHibernate\Linq\DefaultQueryProvider.cs:line 111
   at NHibernate.Linq.NhQueryable`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator() in C:\Development\GitHub\nhibernate-core\src\NHibernate\Linq\NhQueryable.cs:line 65
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NHibernate.Test.NHSpecificTest.GHxxxx.Fixture.CanNotQuery() in C:\Development\GitHub\nhibernate-core\src\NHibernate.Test\NHSpecificTest\GHxxxx\Fixture.cs:line 45

And this is confusing for our developers, because it is an instance of class B that causes this exception.

What is happening is that the AbstractFlushingEntityEventListener is trying to figure out if there are some dirty tracked entities (using IQueryPlan.QuerySpaces), that should be saved prior to execute the query. In this case the QuerySpaces includes instances of class A.
This behavior is correct!

Only I don't get it, that entities not related to the query are being validated during the AutoFlushIfRequired cycle. In our case, instances of Class B are now validated.
You have 2 situations here:
1) None of the dirty entities are related to our query, so no flushing should occur, so no validation should be performed
2) There are dirty entities that are related to our query, so a flush should occur and the validation should also be done for these dirty entities.

It is the first case that is strange, is this behavior functional correct?
At the moment we added some code that suspend's the auto-flushing behavior, but I don't like this code because of the following reasons (there are probably more reasons, but these are for me the most important ones):
1) We have extra nHibernate code that is looking strange in our business layer. The less we see specific ORM code the better. It is in this area that normally nHibernate shines, other ORM's are far more intrusive.
2) The suppressing can lead to errors that are difficult to be found later, we can suppress flushes that should have been flushed before running some queries.

So, can the code be adjusted to allow this situation?
Or, do you say that de current code is behaving correctly?

**Comment by fredericDelaporte** [comment]
I think no validation should occur when there is nothing to flush. Now for actually what is going on, and if there is no deep reason for this behavior, providing a test case would be a good starting point.

**Comment by dvdwouwe** [comment]
There is a testcase written in the text that confirms thé current behaviour

**Comment by fredericDelaporte** [comment]
Ok sorry i have missed it.
