### ISSUE TITLE
OnPreUpdateCollection - Passed entity instance X is not of expected type Y

### ISSUE THREAD

**Issue by marjohansson** [nhibernate/nhibernate-core#2508]
Hi!

When updating from version 5.2.7 to 5.3.2, we get the following error in OnPreUpdateCollection event listener.

Seems to occur when changing a collection in a class (joined subclass) with a lazy property .

Using the lazy property gives us the ProxyForFieldInterceptor and the exception.

at NHibernate.Tuple.Entity.BytecodeEnhancementMetadataPocoImpl.ExtractInterceptor(Object entity)
   at NHibernate.Tuple.Entity.BytecodeEnhancementMetadataPocoImpl.HasAnyUninitializedLazyProperties(Object entity)
   at NHibernate.Tuple.Entity.AbstractEntityTuplizer.ShouldGetAllProperties(Object entity)
   at NHibernate.Tuple.Entity.PocoEntityTuplizer.GetPropertyValues(Object entity)
   at NHibernate.Persister.Entity.AbstractEntityPersister.GetPropertyValues(Object obj)
   at NHibernate.Test.NHSpecificTest.GH2508.AuditEventListener.OnPreUpdateCollection(PreCollectionUpdateEvent event) in 

Thank you for keeping NH alive!

**Comment by bahusoid** [comment]
Can you share a test case(Exception stack trace hints that you already have one)? 

@maca88  Looks like regression after #1946
Shouldn't the check below should use `IsInstanceOf` instead of equality?:
https://github.com/nhibernate/nhibernate-core/blob/9fc784e6a3dac2df3518ca612e461d75d3aca7dc/src/NHibernate/Tuple/Entity/BytecodeEnhancementMetadataPocoImpl.cs#L173-L177

**Comment by marjohansson** [comment]
[AuditEventListener.zip](https://github.com/nhibernate/nhibernate-core/files/5155880/AuditEventListener.zip)

**Comment by maca88** [comment]
> Looks like regression after #1946

Correct.

> Shouldn't the check below should use IsAssignableFrom instead of equality?:

Yes we should, Hibernate [uses isInstance](https://github.com/hibernate/hibernate-orm/blob/162bc7d9dd671d6fc3c596a2ec29c469c1acb7b3/hibernate-core/src/main/java/org/hibernate/tuple/entity/BytecodeEnhancementMetadataPojoImpl.java#L240), which is equivalent to `IsAssignableFrom` in .NET.

@marjohansson thanks for the test case.
