### ISSUE TITLE
Unable to deserialize session if it contains entities with lazy properties

### ISSUE THREAD

**Issue by cremor** [nhibernate/nhibernate-core#2563]
I noticed that sometimes trying to deserialize a session fails with an exception like `SerializationException: The object with ID 223 implements the IObjectReference interface for which all dependencies cannot be resolved. The likely cause is two instances of IObjectReference that have a mutual dependency on each other.`.

I'm not 100% sure about it, but it seems like that happens when the serialized session contains an entity that has lazy properties.

Sadly, the stack trace is not helpful:

    at System.Runtime.Serialization.ObjectManager.GetCompletionInfo(FixupHolder fixup, ObjectHolder& holder, Object& member, Boolean bThrowIfMissing)
    at System.Runtime.Serialization.ObjectManager.CompleteObject(ObjectHolder holder, Boolean bObjectFullyComplete)
    at System.Runtime.Serialization.ObjectManager.DoFixups()
    at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
    at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
    at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream)

I reproduced it with versions 5.2.7 and 5.3.3.

If I find any additional information I'll add it here later.
If anyone has an idea on how to narrow this down to a specific test case, please tell.

**Comment by bahusoid** [comment]
And do you have classes that implement `IObjectReference` in your code?

**Comment by bahusoid** [comment]
And what target framework?

**Comment by cremor** [comment]
No, my code doesn't use `IObjectReference` at all.
Target Framework is .NET 4.8

**Comment by bahusoid** [comment]
And can it be that deserialization happens after entity code is modified (like new properties were added)?

**Comment by bahusoid** [comment]
Also make sure that serialization/deserialization happens for the same NHibernate version.

**Comment by cremor** [comment]
My code flow is

1. Session is serialized.
2. `Flush()` is called.
3. If `Flush()` throws an exception (e.g. unique constraint violation) the session is deserialized.

So there are pending changes in the serialized session, otherwise `Flush()` would have never thrown an exception and therefore the deserialization would have never happened. But as far as I can tell (not 100% sure here) the pending changes don't have to be in the entities that have lazy properties. 

And yes, serialization/deserialization always happens for the same NHibernate version (it's just serialized to a `MemoryStream`).

**Comment by bahusoid** [comment]
No idea what's goin on. I guess you should obtain dump of serialized session that fails  - and then you can test it closely. If it's 100% reproducible or not. And you can provide custom surrogate to check when exception happens and what's inside your dump. Something like this:

```C#
var formatter = new BinaryFormatter
{
	SurrogateSelector = new SerializationInspector()
};
(ISession) formatter.Deserialize(serializedSession)


private class SerializationInspector : System.Runtime.Serialization.SurrogateSelector
{
	public override ISerializationSurrogate GetSurrogate(System.Type type, StreamingContext context, out ISurrogateSelector selector)
	{
		if (
			//typeof(BaseEntity).IsAssignableFrom(type)) &&
			!type.FullName.StartsWith("System.")
		)
			Console.WriteLine("Deserializing type: " + type.FullName);

		return base.GetSurrogate(type, context, out selector);
	}

}

```

**Comment by cremor** [comment]
I've tried your `SurrogateSelector` suggestion but can't see anything obvious wrong with the types that are passed there. The failing session has a few more distinct types, but none of those seem wrong (and they are all just my mapped entity classes, so there are no additional NHibernate types). The order of calls also doesn't seem to indicate anything because the last few types before the exception is thrown are always different.

But I have a 100% reproducible test case in my development system now. And I think that I narrowed it down. The crash only happens all of the following is true:

- An entity is mapped with a lazy property
- The same entity also has two many-to-one reference to **itself** (think of `Predecessor` and `Successor` properties)
- The session that is deserialized contained at least two of those entities and they referenced each other (e.g. `entityA.Successor == entityB` and `entityB.Predecessor == entityA`).

**Comment by bahusoid** [comment]
Good job! I've been able to reproduce it too on net461: https://gist.github.com/bahusoid/55d8dfc3d02abfb270e4228fe50ab480

**Comment by fredericDelaporte** [comment]
Does this happens with the legacy proxy factory too? (`NHibernate.Bytecode.DefaultProxyFactoryFactory`, see [proxyfactory.factory_class](https://nhibernate.info/doc/nhibernate-reference/session-configuration.html#configuration-optional))

**Comment by cremor** [comment]
The session deserialization doesn't throw an exception with the legacy proxy factory in my test case.

But there seems to be another big problem with it, because my entities with lazy properties then have all their properties (not just the lazy ones) reset to the default value after deserialization. Not that it matters since that code is deprecated anyway 😄

**Comment by bahusoid** [comment]
Not really sure what's going on  but with simplified [tests case](https://gist.github.com/bahusoid/55d8dfc3d02abfb270e4228fe50ab480) with only 2 entities `FieldInterceptorObjectReference.GetRealObject` is never called on deserialization (and deserialization ctor too).

**Comment by bahusoid** [comment]
It seems `BinaryFormatter` just can't deserialize  circular references for objects implementing `IObjectReference`

I reproduced this issue with simple classes [here](https://gist.github.com/bahusoid/0f1e1fd25d9d3e5f1a147b0a0fea44cf) imitating work of proxy for field interceptor.

**Comment by fredericDelaporte** [comment]
So this looks as a 5.2 regression, due to switching to the static proxy factory.

**Comment by bahusoid** [comment]
It seems inside  `FieldInterceptorObjectReference.GetBaseData` we should detect field inerceptor members and wrap them in new `FieldInterceptorObjectWrapper` class which has similar functionality of `FieldInterceptorObjectReference` but not implements `IObjectReference` (maybe extract base class from `FieldInterceptorObjectReference`)
Here is example of this implementation: https://gist.github.com/bahusoid/ecdd9119c30fef5e08585761a015b96b

**Comment by cremor** [comment]
> So this looks as a 5.2 regression, due to switching to the static proxy factory.

Maybe not. The legacy proxies also used `IObjectReference`. If #1481 would have been fixed for them they might have shown the same deserialization exception.

**Comment by dimako** [comment]
Any updates on this one? 
We are having a similar issue with 5.3.5, .Net Framework 4.8. When using BinaryFormatter to serialise an object with properties that are proxies and then deserialise it back it throws 

System.ArgumentNullException: 'Value cannot be null.

here is the stack:
   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
   at NHibernate.Proxy.NHibernateProxyFactoryInfo.CreateProxyFactory()
   at NHibernate.Proxy.NHibernateProxyObjectReference.GetRealObject(StreamingContext context)
   at System.Runtime.Serialization.ObjectManager.ResolveObjectReference(ObjectHolder holder)
   at System.Runtime.Serialization.ObjectManager.DoFixups()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream)
   
Thank you

**Comment by bahusoid** [comment]
@dimako It looks like different issue. Most likely exception is thrown here:
https://github.com/nhibernate/nhibernate-core/blob/c8b9ae6e7b4b839b21b22671e47adbba0707f0ad/src/NHibernate/Proxy/NHibernateProxyFactoryInfo.cs#L47

But without reproducible example it's hard to say what's going on.

**Comment by fredericDelaporte** [comment]
> It seems inside  `FieldInterceptorObjectReference.GetBaseData` we should detect field interceptor members and wrap them in new `FieldInterceptorObjectWrapper` class which has similar functionality of `FieldInterceptorObjectReference` but not implements `IObjectReference` (maybe extract base class from `FieldInterceptorObjectReference`)

I think it would break the field interceptor proxy of the deserialized association, and/or cause the entities to be duplicated after deserialization (meaning having two instances representing the same entity).

An other option may be to leverage the `_fieldInterceptor` member capabilities as a workaround. The `GetBaseData` would detect associations and would not directly serialize them (at least not the one-to-one and many-to-one) but just store their id (as the `_fieldInterceptor` exposes the session, it should be doable). After deserialization, the `_fieldInterceptor` would intercept those associations too in order to resolve them from their id and the session when they are accessed. That would require to add some new members to the field interceptor to allow transmitting it the data about associations to intercept after having deserialized the object reference.
We may avoid that extra laziness by instead using an [`IDeserializationCallback`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.serialization.ideserializationcallback) to resolve these associations. (But where should we put it? On the object reference or on the real object? I am not sure about this.)

**Comment by fredericDelaporte** [comment]
Beside being quite complicated, my proposition would not work if the session is closed or if proxied entities have a custom serialization.
Maybe the only way around this is to avoid using `IObjectReference`, if possible.

**Comment by bahusoid** [comment]
> I think it would break the field interceptor proxy of the deserialized association, and/or cause the entities to be duplicated after deserialization (meaning having two instances representing the same entity).

My original attempt was indeed broken and circular references were not properly deserialized. But I believe I've been able to prototype working example:
https://gist.github.com/bahusoid/62f980ea973ca2e44735e33f365d5d56

Some notes:
1) `IObjectReference` objects save the only field  -  [wrapper class](https://gist.github.com/bahusoid/62f980ea973ca2e44735e33f365d5d56#file-program-cs-L48-L49)
2) Nested `IObjectReference` objects are serialized directly as [wrapper classes](https://gist.github.com/bahusoid/62f980ea973ca2e44735e33f365d5d56#file-program-cs-L100-L101)
3) On deserialization wrapper class needs `IDeserializationCallback` for proper restoration of [circular references](https://gist.github.com/bahusoid/62f980ea973ca2e44735e33f365d5d56#file-program-cs-L112-L113)

For proper circular reference detection the same instance of wrapper class should be serialized for the same instance of entity. It' looks like a problem to me. Not sure how to implement it nicely. In prototype it's stored as [field in proxy](https://gist.github.com/bahusoid/62f980ea973ca2e44735e33f365d5d56#file-program-cs-L36). 


> to avoid using IObjectReference, if possible

I guess it's possible by providing our serialization surrogate and/or binder.
