### ISSUE TITLE
BinaryFormatter is not supported in .net5.0

### ISSUE THREAD

**Issue by danielegiallonardo** [nhibernate/nhibernate-core#2603]
Net5.0 applications won't start since BinaryFormatter use is prohibited, as stated [here](https://docs.microsoft.com/it-it/dotnet/core/compatibility/3.1-5.0#binaryformatter-serialization-methods-are-obsolete-and-prohibited-in-aspnet-apps).
Please consider replacing BinaryFormatter with something Net5.0-friendly.

**Comment by bahusoid** [comment]
> It's something AspNet Core related, since .net5.0 console applications don't have such an issue.

Well according to docs you mentioned you can still use it with ASP.NET. You just need to update your csproj file:
>To continue using BinaryFormatter in ASP.NET apps, you can re-enable it in the project file. 
```xml
<PropertyGroup>
  <TargetFramework>net5.0</TargetFramework>
  <!-- Warning: Setting the following switch is *NOT* recommended in web apps. -->
  <EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
</PropertyGroup>
```

**Comment by danielegiallonardo** [comment]
Yes, they've introduced that tag in order to legacy applications to still run until all the references to BinaryFormatter in the depedencies are replaced, but it's still something they strongly DON'T recommend, since BinaryFormatter has security issues and it has been marked as deprecated in .net5+. 
In order to the library to be fully .Net5+-compliant, all the references to BinaryFormatter should be replaced with one of the suggested alternatives.

**Comment by hazzik** [comment]
> BinaryFormatter should be replaced with one of the suggested alternatives.

It _could_ be replaced with one of the alternatives.

NHibernate uses BinaryFormatter in just two places: `SerializableType` and `SerializationHelper`. It is totally safe to enable `BinaryFormatter` if you are not using any of these features.

**Comment by danielegiallonardo** [comment]
I know that a workaround exists, and I'm currently forced to adopt it, but are you suggesting that I should disable for a long-term an application-wide block of a high-risk OWASP reported vulnerability, implemented in a core class that is reported as deprecated (and I expect it to be removed in future versions of the .net sdk)?
Anyway, I'm not asking for a hot-fix, I'm just reporting an existing issue about NHibernate compatibiliy with .net5+.

**Comment by fredericDelaporte** [comment]
Do we actually need to disable that block for running NHibernate on .Net 5? I think it is not even needed.

The application will run just fine provided it does not use the few features of NHibernate which use `BinaryFormatter`. If it uses it, it will raise a `NotImplementedException` according to your link, and so you will be easily able to detect the offending part in your application for ceasing to use the few features relying on `BinaryFormatter`.

So  I do not see a reason for enabling binary formatter in .Net 5 if your code does not use any feature requiring binary serialization. That should not prevent using NHibernate at all, since it seems to be a runtime check triggered only on actual use of a binary formatter.

**Comment by danielegiallonardo** [comment]
Unfortunately the asp.net app won't start at all, whether you use a feature requiring binary serialization or not (BTW, I don't use it), throwing the following exception (an InnerException thrown inside a FluentConfigurationException) when calling BuildConfiguration():

"NotSupportedException: BinaryFormatter serialization and deserialization are disabled within this application. See https://aka.ms/binaryformatter for more information."

I suppose the only fact you reference (somewhere in your code) the BinaryFormatter class causes the app to block at the startup.

**Comment by bahusoid** [comment]
> I suppose the only fact you reference (somewhere in your code) the BinaryFormatter class causes the app to block at the startup.

I doubt it. Can you share full stack trace? I suspect it's FluentNhibernate to blame and `BinaryFormatter` is actually used there.

**Comment by danielegiallonardo** [comment]
Ok, it seems you're right. Here's the full stacktrace.

```
FluentNHibernate.Cfg.FluentConfigurationException: An invalid or incomplete configuration was used while creating a SessionFactory. Check PotentialReasons collection, and InnerException for more detail.


 ---> System.NotSupportedException: BinaryFormatter serialization and deserialization are disabled within this application. See https://aka.ms/binaryformatter for more information.
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph)
   at FluentNHibernate.Utils.Extensions.DeepClone[T](T obj)
   at FluentNHibernate.Mapping.SubclassMap`1.FluentNHibernate.Mapping.Providers.IIndeterminateSubclassMappingProvider.GetSubclassMapping(SubclassType type)
   at FluentNHibernate.Visitors.SeparateSubclassVisitor.ProcessClass(ClassMapping mapping)
   at FluentNHibernate.MappingModel.ClassBased.ClassMapping.AcceptVisitor(IMappingModelVisitor visitor)
   at FluentNHibernate.Visitors.DefaultMappingModelVisitor.Visit(ClassMapping classMapping)
   at FluentNHibernate.MappingModel.HibernateMapping.AcceptVisitor(IMappingModelVisitor visitor)
   at FluentNHibernate.Visitors.DefaultMappingModelVisitor.<Visit>b__10_0(HibernateMapping x)
   at FluentNHibernate.Utils.CollectionExtensions.Each[T](IEnumerable`1 enumerable, Action`1 each)
   at FluentNHibernate.Visitors.DefaultMappingModelVisitor.Visit(IEnumerable`1 mappings)
   at FluentNHibernate.PersistenceModel.ApplyVisitors(IEnumerable`1 mappings)
   at FluentNHibernate.PersistenceModel.BuildMappings()
   at FluentNHibernate.PersistenceModel.EnsureMappingsBuilt()
   at FluentNHibernate.PersistenceModel.Configure(Configuration cfg)
   at FluentNHibernate.Cfg.FluentConfiguration.BuildConfiguration()
   --- End of inner exception stack trace ---
   at FluentNHibernate.Cfg.FluentConfiguration.BuildConfiguration()
   at Asf.PublicApps.Infrastructure.Extensions.NHibernateExtensions.AddNHibernate[T](IServiceCollection services, String connectionString)
   at Asf.PublicApps.Common.BL.ServiceCollectionExtensions.RegisterBLServices(IServiceCollection services, IConfiguration configuration) in G:\Repos\ASF\Backend\Asf.PublicApps.Common.BL\ServiceCollectionExtensions.cs:line 59

```

**Comment by oyzar** [comment]
While FluentNhibernate's use of BinaryFormater is more obvious as it fails on startup, the usages in NHibernate should still be changed. It's used in 5 places:
NHibernate.Type.SerializableType.FromBytes
NHibernate.Type.SerializableType.ToBytes
NHibernate.Util.SerializationHelper.CreateFormatter
NHibernate.Util.SerializationHelper.Deserialize
NHibernate.Util.SerializationHelper.Serialize

**Comment by danielegiallonardo** [comment]
Here is the same issue in the FluentNHibernate repo: [https://github.com/nhibernate/fluent-nhibernate/issues/479](https://github.com/nhibernate/fluent-nhibernate/issues/479)
I think we can close here. Thanks

**Comment by gokhanabatay** [comment]
I have the same issue with .net 5.0 NHibernate second level cache mechanism. What could we do without except "EnableUnsafeBinaryFormatterSerialization=true" at project file?

```
at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph)
   at NHibernate.Util.SerializationHelper.Serialize(Object obj)
   at NHibernate.Caches.Common.BinaryCacheSerializer.Serialize(Object value)
   at NHibernate.Caches.StackExchangeRedis.DistributedLocalCacheRegionStrategy.ExecuteOperation(String cacheKey, Object value, Int64 timestamp, Int32 clientId, Boolean publish, Boolean remove)
   at NHibernate.Caches.StackExchangeRedis.DistributedLocalCacheRegionStrategy.TryPutLocal(String cacheKey, Object value, Int64 timestamp, Int32 clientId, Boolean publish)
   at NHibernate.Caches.StackExchangeRedis.DistributedLocalCacheRegionStrategy.ExecutePut(String cacheKey, Object value)
   at NHibernate.Caches.StackExchangeRedis.AbstractRegionStrategy.Put(Object key, Object value)
   at NHibernate.Caches.StackExchangeRedis.DistributedLocalCacheRegionStrategy.ExecutePutMany(Object[] keys, Object[] values)
   at NHibernate.Caches.StackExchangeRedis.AbstractRegionStrategy.PutMany(Object[] keys, Object[] values)
   at NHibernate.Caches.StackExchangeRedis.RedisCache.PutMany(Object[] keys, Object[] values)
   at NHibernate.Cache.UpdateTimestampsCache.SetSpacesTimestamp(IReadOnlyCollection`1 spaces, Int64 ts)
   at NHibernate.Cache.UpdateTimestampsCache.PreInvalidate(IReadOnlyCollection`1 spaces)
   at Framework.Core.DataAccess.Cache.UpdateTimestampsCache.PreInvalidate(IReadOnlyCollection`1 spaces) in /jenkins/workspace/Paycore.Ocean.Develop/Backend/Framework/Framework.Core/DataAccess/Cache/UpdateTimestampsCache.cs:line 51
   at NHibernate.Engine.ActionQueue.PreInvalidateCaches()
   at NHibernate.Engine.ActionQueue.ExecuteActions()
   at NHibernate.Event.Default.AbstractFlushingEventListener.PerformExecutions(IEventSource session)
   at NHibernate.Event.Default.DefaultFlushEventListener.OnFlush(FlushEvent event)
   at NHibernate.Impl.SessionImpl.Flush()
   at Framework.Core.DataAccess.UnitOfWork.UnitOfWorkProvider.Commit() in /jenkins/workspace/Paycore.Ocean.Develop/Backend/Framework/Framework.Core/DataAccess/UnitOfWork/UnitOfWorkProvider.cs:line 152
   at Framework.Core.DataAccess.UnitOfWork.UnitOfWorkProvider.Execute(UnitOfWorkAttribute unitOfWork, Action action, ILogger logger) in /jenkins/workspace/Paycore.Ocean.Develop/Backend/Framework/Framework.Core/DataAccess/UnitOfWork/UnitOfWorkProvider.cs:line 279
   at Framework.Core.DataAccess.UnitOfWork.UnitOfWorkInterceptor.Intercept(IInvocation invocation) in /jenkins/workspace/Paycore.Ocean.Develop/Backend/Framework/Framework.Core/DataAccess/UnitOfWork/UnitOfWorkInterceptor.cs:line 152
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.ICfgExchangeFunctionCodeDefServiceProxy.Merge(CfgExchangeFunctionCodeDef entity)
   at Framework.Facilities.Web.Api.Controller.BaseController`3.Update(TEntity entity) in /jenkins/workspace/Paycore.Ocean.Develop/Backend/Framework/Framework.Facilities.Web.Api/Controller/BaseController.cs:line 59
   at lambda_method329(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
```

**Comment by fredericDelaporte** [comment]
@gokhanabatay, this is not a NHibernate issue but a cache question, you should have opened your case [there](https://github.com/nhibernate/NHibernate-Caches).
But anyway binary serialization is only a default method of serialization for some caches. You can choose another cache implementation, or configure another serializer, depending on the actual cache you use. Just read their [documentation](https://nhibernate.info/doc/nhibernate-reference/caches.html): there is a `cache.serializer` setting for `StackExchangeRedis`, and a `JsonSerializer` is available in a NuGet package.

**Comment by fredericDelaporte** [comment]
@oyzar 
> the usages in NHibernate should still be changed.

Why? Can you elaborate on this?

`SerializableType` is meant to binary serialize, there is no point in "changing" it. No one forces you to use this type with NHibernate in your mappings. Just do not use it. We will obviously flag it as obsolete at some point like `BinaryFormatter` is, but that is all.

`SerializationHelper` is just an utility for those needing binary serialization. NHibernate does not use it directly. So that is the same: there is no point in changing it, just do not use it. And it will just be flagged obsolete too at some point, I guess when NHibernate will target directly .Net 5.

**Comment by oyzar** [comment]
It would be better to change to an implementation that doesn't use an unsafe part of the .net API. There are alternatives listed here: https://aka.ms/binaryformatter are none of those possible to use?

**Comment by fredericDelaporte** [comment]
There are not any such implementations, as you could infer by reading your link.
The recommended alternatives are serialization to XML or JSON, neither of which are a binary serialization. The other alternatives are put in a **Dangerous alternatives** section, because they suffer the same threats than the `BinaryFormatter`.

Having some code referencing those unsafe types does not cause the project to be unsafe, since the default in .Net 5 will be to block the execution of those unsafe features. People trying to use them will get appropriate warning, and that will be their responsibility and freedom if they choose to use them and disable the block for doing this.

This change in .Net 5 means binary serialization should no more be used. The two types using it in NHibernate are to be used only by those needing binary serialization, so the only action we should take about them is to flag them as obsolete once targeting .Net 5, and eventually offer some alternative if needed.

By example, `SerializableType` is a fallback type when NHibernate encounters an entity class with a property having an unsupported type. Ending-up throwing a `NotImplementedException` in such case makes sense, but we could consider adding something like a `JsonType` and use it as a fallback instead of `SerializableType`. (Changing this fallback will be a possible breaking change.)

**Comment by sirpenski** [comment]
Stupid nanny state incels. Without the binary serialization, deserialization, you can't efficiently store complex session data objects. And don't say cookie either because anything on user side is unsecure and costs thousands of cycles to verify integrity.  Elimination of this feature turns asp net core/net 5 efficiency into that of an uncompiled php script when session variables are used. Geez.

**Comment by ameer-thasthahir** [comment]
> > It's something AspNet Core related, since .net5.0 console applications don't have such an issue.
> 
> Well according to docs you mentioned you can still use it with ASP.NET. You just need to update your csproj file:
> 
> > To continue using BinaryFormatter in ASP.NET apps, you can re-enable it in the project file.
> 
> ```
> <PropertyGroup>
>   <TargetFramework>net5.0</TargetFramework>
>   
>   <EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
> </PropertyGroup>
> ```

Still it's not working

**Comment by walter-psjr** [comment]
I had this error using the package NHibernate.Caches.StackExchangeRedis and I solved it by configuring JSON Serializer instead (package NHibernate.Caches.Util.JsonSerializer).

**Comment by ondravondra** [comment]
The `SerializableType` is still used when doing a query like this:
```
DateTime lastHour = ...; // local variable or parameter
ses.QueryOver<...>()
  .Where .... 
  .SelectList(list => list
    .Select(() => lastHour)
    ....
  )
...
```

Here it calls `QueryOverProjectionBuilder::Select(Expression<Func<object>> expression)` that creates a `ConstantProjection` with a value of type `System.Object`. The value is of type `System.Object` because the `expression` argument of the `QueryOverProjectionBuilder` is of type `Expression<Func<object>>`. The `ConstantProjection` constructor then calls `NHibernateUtil.GuessType(value.GetType())`, `value.GetType()` is now `System.Object` and the `GuessType` method returns `SerializableType`. Running this code in dotnet10 throws a `PlatformNotSupportedException`

**Comment by ValResnick** [comment]
Hello everyone,

from my perspective, this topic is more relevant than ever. Due to its fundamental design flaws, the BinaryFormatter can never be considered secure and should therefore not remain part of NHibernate in the long term. In particular, its usage is consistently flagged as a vulnerability in penetration tests.

Even applications that do not actively use the Serializable type are indirectly affected by the risks associated with the BinaryFormatter.

I therefore propose introducing an abstraction that explicitly shifts responsibility for serialization to the application layer. Only the application context can make valid decisions about how specific types should be serialized in a secure and correct manner.

For legacy applications, the BinaryFormatter could remain available as an optional fallback. However, the default implementation should be intentionally restrictive and throw an exception (“security first”) to clearly indicate that an explicit serialization strategy is required.

Conceptually, this approach would be comparable to IUserType, but focused solely on serialization and deserialization. Within this abstraction, it would also be possible to implement application-specific migration strategies, including during live operation.

If this proposal sounds reasonable, I would be willing to prepare a corresponding pull request.

I’m looking forward to your feedback.

**Comment by fredericDelaporte** [comment]
> For legacy applications, the BinaryFormatter could remain available as an optional fallback.

Meaning it stays in NHibernate and change nothing about "not remain part of NHibernate in the long term"?

By the way its usage in most case is already a fallback very likely unintended by the user and so, letting it throw (current default behavior under net5 and higher) looks fine to me.

Anyway, I was already stating in a previous comment years ago this:

> This change in .Net 5 means binary serialization should no more be used. The two types using it in NHibernate are to be used only by those needing binary serialization. So the only action we should take about them is to flag them as obsolete once targeting .Net 5, and eventually offer some alternative if needed.
>
> By example, SerializableType is a fallback type when NHibernate encounters an entity class with a property having an unsupported type. Ending-up throwing a NotImplementedException in such case makes sense, but we could consider adding something like a JsonType and use it as a fallback instead of SerializableType. (Changing this fallback will be a possible breaking change.)

The situation has not moved because no one has taken time to work on it. That is all.

**Comment by ValResnick** [comment]
Thanks for the clarification. I think we’re actually closer on this than it might seem at first glance.

My main concern is less about whether the BinaryFormatter still exists in the codebase short-term, and more about the fact that its usage currently happens implicitly — especially through fallbacks like SerializableType. That, in my view, is the core issue.

Even though binary serialization is effectively disabled or throws under .NET 5+, the behavior remains structurally problematic:

- Developers can end up on this path unintentionally, without making a conscious decision
- Marking things as obsolete or throwing at runtime increases visibility, but doesn’t remove the underlying coupling
- Security issues arise precisely because of this lack of transparency

We actually ran into this ourselves: we were using the BinaryFormatter in NHibernate indirectly without even realizing it. From my perspective, this clearly shows that the current fallback behavior is not transparent enough in practice and can lead to real risks.

The goal of the proposal is therefore to eliminate this implicit usage entirely and shift responsibility clearly to the application layer. NHibernate, in my opinion, cannot make a safe or semantically correct default decision about serialization — that always depends on the specific application context.

Replacing it with something like a JsonType as a new fallback would only shift the problem: we would still have implicit behavior, just with a different format. That’s exactly what should be avoided.

Instead, I believe an explicit abstraction (similar in spirit to IUserType, but focused on serialization) would be the better approach. It would:

- force an explicit decision by the application
- eliminate hidden fallbacks
- allow for application-specific and even live migration strategies

A similar principle can be seen in EF Core: serialization and conversion are configured explicitly via value converters, not handled through implicit fallbacks. This forces conscious decisions and avoids the kind of hidden behavior we’re currently dealing with here.

Regarding the BinaryFormatter itself, I think moving it out of the NHibernate core would be a reasonable approach. Applications that still depend on it could opt in explicitly by referencing an additional package or component.

This would:

- remove implicit usage from the core
- establish clear responsibility boundaries
- still support legacy scenarios where needed

I’m aware that this would be a breaking change, but it could be communicated clearly and would significantly improve long-term clarity and security.

So the goal would be:

- no implicit serialization fallbacks in the core
- clear separation of responsibilities
- “secure by default” through enforced explicitness

If this direction makes sense, I’d be happy to work this out in more detail and prepare a concrete proposal or PR.

**Comment by fredericDelaporte** [comment]
This sounds good to me.

**Comment by fredericDelaporte** [comment]
Obsoleted by #3745
