### ISSUE TITLE
SchemaValidator Validate concurrency issue

### ISSUE THREAD

**Issue by zdenotirc** [nhibernate/nhibernate-core#2670]
Following code is not thread-safe, throws exception when called concurrently.

`new SchemaValidator(_sessionFactory.Configuration).Validate()`

StackTrace:
Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at NHibernate.Cfg.Configuration.SecondPassCompile()
   at NHibernate.Cfg.Configuration.ValidateSchema(Dialect dialect, IDatabaseMetadata databaseMetadata)
   at NHibernate.Tool.hbm2ddl.SchemaValidator.Validate()

**Comment by gliljas** [comment]
That is very likely so, and I guess it could be fixed quite easily, but was is the use case where such a thing is called concurrently?

**Comment by zdenotirc** [comment]
Schema is validated with some of the requests. It is request based environment (asp.net core=implicit parallelism)

Example:
`command.Validate()
  .Then(_ => _service.ValidateSchema())
  .Then(_ => DoWork());`

**Comment by fredericDelaporte** [comment]
This class is not thread safe, you should ensure it is not run concurrently. Moreover validating many times is quite unusual, and most likely a waste of computing resources.
