### ISSUE TITLE
The column 'Currency_ID' has already been added in this SQL builder (Parameter 'columnName')

### ISSUE THREAD

**Issue by NikitaEgorov** [nhibernate/nhibernate-core#2726]
My legacy project has very strange DB Scheme :)
Base table `Items` and all object inherit from this table for example

class  Currency : Items{}
In DB: table Items and table Currencies
But Id from Currencies reused as Id for localization as Caption 🤬
And I get this HBM and exception

```xml
<hibernate-mapping xmlns="urn:nhibernate-mapping-2.2">
  <class xmlns="urn:nhibernate-mapping-2.2" dynamic-update="true" name="Domain.Currency, Domain, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" table="Items">
    <id name="Id" type="System.Int32, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e" unsaved-value="0">
      <column name="Item_ID" not-null="true" />
      <generator class="identity" />
    </id>
    <property name="Guid" type="System.Guid, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e">
      <column name="Item_Guid" />
    </property>
    <property name="Version" type="System.Int64, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e">
      <column name="Item_Version" />
    </property>
    <join table="Currencies">
      <key>
        <column name="Currency_ID" />
      </key>
      <property name="Code" type="System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e">
        <column name="Currency_Code" />
      </property>
      <many-to-one cascade="none" class="Domain.Caption, Domain, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" name="Caption">
        <column name="Currency_ID" />
      </many-to-one>
    </join>
  </class>
</hibernate-mapping>
```

and NHibernate 5.3.8
Exception: **The column 'Currency_ID' has already been added in this SQL builder (Parameter 'columnName')**
```c#
   at NHibernate.SqlCommand.SqlInsertBuilder.AddColumnWithValueOrType(String columnName, Object valueOrType)
```

**Comment by NikitaEgorov** [comment]
```c#
   at NHibernate.SqlCommand.SqlInsertBuilder.AddColumnWithValueOrType(String columnName, Object valueOrType)
   at NHibernate.SqlCommand.SqlInsertBuilder.AddColumns(String[] columnNames, Boolean[] insertable, IType propertyType)
   at NHibernate.Persister.Entity.AbstractEntityPersister.GenerateInsertString(Boolean identityInsert, Boolean[] includeProperty, Int32 j)
   --- End of inner exception stack trace ---
   at NHibernate.Persister.Entity.AbstractEntityPersister.GenerateInsertString(Boolean identityInsert, Boolean[] includeProperty, Int32 j)
   at NHibernate.Persister.Entity.AbstractEntityPersister.PostInstantiate()
   at NHibernate.Persister.Entity.SingleTableEntityPersister.PostInstantiate()
   at NHibernate.Impl.SessionFactoryImpl..ctor(Configuration cfg, IMapping mapping, Settings settings, EventListeners listeners)
   at NHibernate.Cfg.Configuration.BuildSessionFactory()
   at FluentNHibernate.Cfg.FluentConfiguration.BuildSessionFactory()
```

**Comment by NikitaEgorov** [comment]
if add `insert="false" name="Caption" update="false"` to `<many-to-one cascade="none" class="Domain.Caption, Domain, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" name="Caption">`
All is working fine

**Comment by hazzik** [comment]
Hi @NikitaEgorov this is a documented possible breaking change in 5.2.0

https://github.com/nhibernate/nhibernate-core/blob/d2599c615237fe7b8ee1a14c152374f7351562d3/releasenotes.txt#L624-L629

The solution you have found is exactly what is recommended.
