### ISSUE TITLE
Unable to add a parameter to a SQLCriterion 

### ISSUE THREAD

**Issue by RobWalker** [nhibernate/nhibernate-core#2839]
I have a working expression:

```
var filter_sql = $@"normalize_emails({{{alias}}}.AxEmails) @> to_jsonb(normalize_email('{v}'))";

return new SQLCriterion(
  new NHibernate.SqlCommand.SqlString(filter_sql), 
  new object[0], 
  new NHibernate.Type.IType[0]);
```

This is embedding the user supplied (albeit sanitized) `v` into the SQL string and I would sooner pass it as a parameter, but I can't get this to work:

```
var filter_sql = $@"normalize_emails({{{alias}}}.AxEmails) @> to_jsonb(normalize_email(?))";

return new SQLCriterion(
  new NHibernate.SqlCommand.SqlString(filter_sql), 
  new object[1] { v }, 
  new NHibernate.Type.IType[1] { NHibernateUtil.String });
```

Throws an error:

```
System.ArgumentOutOfRangeException
  HResult=0x80131502
  Message=Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
  Source=System.Private.CoreLib
  StackTrace:
   at System.ThrowHelper.ThrowArgumentOutOfRange_IndexException()
   at NHibernate.Criterion.SQLCriterion.ToSqlString(ICriteria criteria, ICriteriaQuery criteriaQuery)
   at NHibernate.Loader.Criteria.CriteriaQueryTranslator.GetWhereCondition()
   at NHibernate.Loader.Criteria.CriteriaJoinWalker..ctor(IOuterJoinLoadable persister, CriteriaQueryTranslator translator, ISessionFactoryImplementor factory, ICriteria criteria, String rootEntityName, IDictionary`2 enabledFilters)
   at NHibernate.Criterion.SubqueryExpression.ToSqlString(ICriteria criteria, ICriteriaQuery criteriaQuery)
   at NHibernate.Loader.Criteria.CriteriaQueryTranslator.GetWhereCondition()
   at NHibernate.Loader.Criteria.CriteriaJoinWalker..ctor(IOuterJoinLoadable persister, CriteriaQueryTranslator translator, ISessionFactoryImplementor factory, ICriteria criteria, String rootEntityName, IDictionary`2 enabledFilters)
   at NHibernate.Loader.Criteria.CriteriaLoader..ctor(IOuterJoinLoadable persister, ISessionFactoryImplementor factory, CriteriaImpl rootCriteria, String rootEntityName, IDictionary`2 enabledFilters)
   at NHibernate.Impl.SessionImpl.<ListAsync>d__73`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

Any suggestions?

**Comment by bahusoid** [comment]
`SqlString` is not properly created. You need to use `new SQLCriterion(SqlString.Parse(filter_sql), ...` to properly detect parameters in string. Or better use `Expression.Sql(filter_sql, ...` methods which hide such implementation detail.
