### ISSUE TITLE
Custom Enum IUserType mapping fails on Query with expression

### ISSUE THREAD

**Issue by caccorsi** [nhibernate/nhibernate-core#2850]
Hi, 
We're using a custom type IUserType implementation to map enums as two values. 1: its numeric value for business logic and 2: A string value for reporting purposes. The string value is denormalized data and is not needed to hydrate the value back from the database. It should only be updated on Save. Additionally our requirements must respect an Enum's underlying numeric type - any of : byte, short, int and long. Our custom type EnumMap correctly persists (.Save) and retrieves (.Get) a single entity including properly deploying the correct SQL type for the enum's underlying numeric type. However when we try and query (with an expression) using the member mapped by the custom type, we get a cast error way down in the SQL statement. I don't have that error but it looks like the assembled SQL statement tries to concatenate the two values ( mapped by the custom type) before it tries to cast (in SQL) them to the database numeric value type. Ideally, we would want to ignore the string (denormalized) value in this query. See the psuedo code below. 

Enum definition
```
public enum Direction : byte  
  {  
      North = 0,  
      South = 1,  
      East = 2,  
      West = 3  
  }
```

Class def
```
  public class Point  
  {
     public virtual int Id {get; set;}
     public virtual string Name {get; set;}
     public virtual Direction DirAsValue {get; set;}
     public virtual Direction DirAsMap {get; set;}
  }
```

Mapping
```
  public PointMap() : ClassMap<Point>
  {
  	Table("Point");
  	Id(x => x.Id).GeneratedBy.GuidComb();
  	Map(x => x.Name).Column("Name");
  	Map(x => x.DirectionAsValue).Column("DirAsValue").CustomType(typeof(byte));
  	Map(x => x.DirectionAsMap).Columns.Add("DirAsMap").Columns.Add("DirAsMap_Name").CustomType<EnumMap<Direction,byte>>();
  }
```
Custom IUserType
```
public class EnumMap<TEnumType, TNumericType> : IUserType where TEnumType : Enum
    {
        private static readonly Dictionary<Type, PrimitiveType> _typeMap = new Dictionary<Type, PrimitiveType>();
        static EnumMap()
        {
            _typeMap.Add(typeof(byte), NHibernateUtil.Byte);
            _typeMap.Add(typeof(short), NHibernateUtil.Int16);
            _typeMap.Add(typeof(int), NHibernateUtil.Int32);
            _typeMap.Add(typeof(long), NHibernateUtil.Int64);
        }

        public EnumMap()
        {
            if (!_typeMap.ContainsKey(typeof(TNumericType)))
                throw new Exception($"EnumMap Error: The numeric type ({typeof(TNumericType).Name}) for Enum ({typeof(TEnumType).Name}) is not a supported persistent type. Use one of: byte, short, int, long.");
        }

        // return numeric type + string
        public SqlType[] SqlTypes => new[] { GetDbType().SqlType, NHibernateUtil.String.SqlType };

        public Type ReturnedType => typeof(TEnumType);


        public object NullSafeGet(DbDataReader rs, string[] names, ISessionImplementor session, object owner)
        {
            TNumericType numericValue;

            if (rs.IsDBNull(rs.GetOrdinal(names[0]))) // default value when null
                numericValue = Enum.GetValues(typeof(TEnumType)).Cast<TNumericType>().Min();
            else
                numericValue = (TNumericType)GetDbType().NullSafeGet(rs, names[0], session, owner);

            TEnumType enumValue = (TEnumType)Enum.ToObject(typeof(TEnumType), numericValue);

            return enumValue;
        }

        public void NullSafeSet(DbCommand cmd, object value, int index, ISessionImplementor session)
        {
            if (value == null)
                return;

            // write both numeric and string values
            TNumericType numericValue = (TNumericType)(dynamic)(TEnumType)value;
            string stringValue = Enum.GetName(typeof(TEnumType), numericValue);

            GetDbType().NullSafeSet(cmd, numericValue, index++, session);
            NHibernateUtil.String.NullSafeSet(cmd, stringValue, index, session);
        }

        public object DeepCopy(object value)
        {
            return value;
        }

        public bool IsMutable
        {
            get { return false; }
        }

        public object Disassemble(object value)
        {
            return value;
        }

        public object Assemble(object cached, object owner)
        {
            return cached;
        }

        public object Replace(object original, object target, object owner)
        {
            return original;
        }

        public new bool Equals(object x, object y)
        {
            if (x == null && y == null)
                return true;

            if (x == null || y == null)
                return false;

            if (x == y || x.Equals(y))
                return true;

            return false;
        }

        public int GetHashCode(object x)
        {
            return (x != null) ? x.GetHashCode() : 0;
        }

        private PrimitiveType GetDbType()
        {
            return _typeMap[typeof(TNumericType)];
        }
    }
```

Test code
```
        [TestMethod]
        public void EnumMappingTest()
        {
            ISession session = null; // get session. 
	    var point = new Point
	    {
		Name = "Test",
		DirectionAsValue = Direction.North,
		DirectionAsMap = Direction.South       
	    };
	   // create / commit
	   session.Save(point);
	   session.Evict(point);
	   var pointDb = session.Get(point.Id);

	   // both enum types are writen and read from the database as expected. 
            Assert.AreEqual(Direction.North, pointDb.DirectionAsValue);
            Assert.AreEqual(Direction.South, pointDb.DirectionAsMap);


	    // expression for default enum mapping
            Expression<Func<Point, bool>> doesWork => f.DirectionAsValue == Direction.North;

	    // expression for custom enum mapping
            Expression<Func<Point, bool>> doesNotWork= f => f.DirectionAsMap == Direction.South;

	  // succeeds
	   var resultWorking = session.Query(doesWork);
	  // fails, on the database layer, the SQL tries to concatenate both DirAsMap and  DirAsMap_Name as Int	
	   var resultNotWorking = session.Query(doesNotWork);

        }
```

Stack trace
```
Unable to cast object of type 'System.Int32' to type 'Test.Direction'.

   at NHibernate.Loader.Loader.DoList(ISessionImplementor session, QueryParameters queryParameters, IResultTransformer forcedResultTransformer, QueryCacheResultBuilder queryCacheResultBuilder)
   at NHibernate.Loader.Loader.DoList(ISessionImplementor session, QueryParameters queryParameters)
   at NHibernate.Loader.Loader.ListIgnoreQueryCache(ISessionImplementor session, QueryParameters queryParameters)
   at NHibernate.Loader.Loader.List(ISessionImplementor session, QueryParameters queryParameters, ISet`1 querySpaces)
   at NHibernate.Loader.Hql.QueryLoader.List(ISessionImplementor session, QueryParameters queryParameters)
   at NHibernate.Hql.Ast.ANTLR.QueryTranslatorImpl.List(ISessionImplementor session, QueryParameters queryParameters)
   at NHibernate.Engine.Query.HQLQueryPlan.PerformList(QueryParameters queryParameters, ISessionImplementor session, IList results)
   at NHibernate.Impl.SessionImpl.List(IQueryExpression queryExpression, QueryParameters queryParameters, IList results, Object filterConnection)
   at NHibernate.Impl.SessionImpl.List(IQueryExpression queryExpression, QueryParameters queryParameters, IList results)
   at NHibernate.Impl.AbstractSessionImpl.List(IQueryExpression queryExpression, QueryParameters parameters)
   at NHibernate.Impl.AbstractQueryImpl2.List()
   at NHibernate.Linq.DefaultQueryProvider.ExecuteQuery(NhLinqExpression nhLinqExpression, IQuery query, NhLinqExpression nhQuery)
   at NHibernate.Linq.DefaultQueryProvider.ExecuteQuery(NhLinqExpression nhLinqExpression, IQuery query)
   at NHibernate.Linq.DefaultQueryProvider.Execute(Expression expression)
   at NHibernate.Linq.DefaultQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source)
   at Tests.QueryFactoryByEnumExpressionTest() in C:\Tests\ModelTests.cs:line 568
```

Thank you, 
Carlo Accorsi

**Comment by caccorsi** [comment]
Hi All - is there any guidance someone might provide? I could make an attempt at a PR if I had some direction. Thank you.

**Comment by bahusoid** [comment]
Are you using latest NHibernate 5.3.9? Does it fail the same with 5.2 version?

**Comment by caccorsi** [comment]
Using FluentNHibernate 3.1.0 which has a dependency to NH 5.3.3..

**Comment by fredericDelaporte** [comment]
Add an explicit dependency on NH 5.3.9, it should overrule the fluent dependency version.

**Comment by caccorsi** [comment]
Hi, your suggestion worked! However a bug in our own code was was also contributing to the problem. 
The EnumMap.NullSafeSet was trying to cast a boxed int to a byte which compiles but fails at runtime. 

```
            int i1 = 1;
            object i2 = i1;
            byte b1 = (byte)i1; // yes
            byte b2 = (byte)i2; // no
```

Thank you for your time and I attached a working example of what I was trying to do for your reference. 
Build the solution and run the single test. 
[EnumApp.zip](https://github.com/nhibernate/nhibernate-core/files/6927688/EnumApp.zip)


Thanks!
