### ISSUE TITLE
InvalidCastException when inserting entities referenced by interface mapped to one table (TPH) using IManyToOneMapper.Class()

### ISSUE THREAD

**Issue by andrejkudinov** [nhibernate/nhibernate-core#2908]
InvalidCastException is thrown during `IStatelessSession.Insert()`.

### Description

To demonstrate the issue, I created a minimal sample project (attached to this issue):
[NHibernateBugTest.zip](https://github.com/nhibernate/nhibernate-core/files/7115211/NHibernateBugTest.zip)

There are two mapped concrete classes `Programmer` and `Manager` implementing the same interface `IPerson` and also a base class `PersonBase` (does not implement the `IPerson` interface). The class hierarchy is mapped by code to a DB using the table-per-class-hierarchy (TPH) approach using discriminators.

There are 3 mapping classes for this hierarchy:
* PersonMapping : ClassMapping<Person>
* ManagerMapping : SubclassMapping<Manager>
* ProgrammerMapping : SubclassMapping<Programmer>

There's another mapped class `Group` that references either `Programmer` or `Manager` using the interface `IPerson`.
This reference is mapped in `GroupMapping` as follows:

```
ManyToOne(x => x.Leader, map =>
{
    map.Column("`Person`");
    map.Class(typeof(Programmer));
    map.Class(typeof(Manager));
});
```

The interface `IPerson` is not mapped directly, this is why `map.Class()` statements are used in `GroupMapping`.

This code works without any problems for NHibernate version 5.2.7 but it throws in versions 5.3.0+:
`System.InvalidCastException: 'Unable to cast object of type 'NHibernateBugTest.Entities.Programmer' to type 'NHibernateBugTest.Entities.Manager'.'`

The exception is thrown only when I try to insert `Group` entity referencing an instance of `Manager`. If the order of `map.Class()` statements is changed in the mapping, the problem appears only when inserted `Group` entity references a `Programmer` instance.

This issue is reproducible using a stateless session. I did not test it using a stateful session.

### Question
Is this a bug or a breaking change? I looked at this forum and also release notes but didn't find any mentions about this issue.

**Comment by bahusoid** [comment]
I didn't look in to it. Just a quick note: 

```C#
    map.Class(typeof(Programmer));
    map.Class(typeof(Manager));
```

Such mapping is invalid. Only one `Class` is supported. So I believe it's treated as `map.Class(typeof(Manager))` in both 5.2 and 5.3+ versions.

**Comment by andrejkudinov** [comment]
I may be using it the way it is not supposed to be used. What surprises me is that it practically worked in 5.2.7 and the older versions. In my sample project, it can be verified just by downgrading the NHibernate NuGet package to 5.2.7.

**Comment by hazzik** [comment]
```text
NHibernate.PropertyValueException : Error dehydrating property value for NHibernateBugTest.Entities.Group.Leader
  ----> System.InvalidCastException : Unable to cast object of type 'NHibernateBugTest.Entities.Programmer' to type 'NHibernateBugTest.Entities.Manager'.
   at NHibernate.Persister.Entity.AbstractEntityPersister.Dehydrate(Object id, Object[] fields, Object rowId, Boolean[] includeProperty, Boolean[][] includeColumns, Int32 table, DbCommand statement, ISessionImplementor session, Int32 index) in C:\Projects\Private\nhibernate-core\src\NHibernate\Persister\Entity\AbstractEntityPersister.cs:line 2803
   at NHibernate.Persister.Entity.AbstractEntityPersister.Insert(Object id, Object[] fields, Boolean[] notNull, Int32 j, SqlCommandInfo sql, Object obj, ISessionImplementor session) in C:\Projects\Private\nhibernate-core\src\NHibernate\Persister\Entity\AbstractEntityPersister.cs:line 3119
   at NHibernate.Persister.Entity.AbstractEntityPersister.Insert(Object id, Object[] fields, Object obj, ISessionImplementor session) in C:\Projects\Private\nhibernate-core\src\NHibernate\Persister\Entity\AbstractEntityPersister.cs:line 3533
   at NHibernate.Impl.StatelessSessionImpl.Insert(String entityName, Object entity) in C:\Projects\Private\nhibernate-core\src\NHibernate\Impl\StatelessSessionImpl.cs:line 497
   at NHibernate.Impl.StatelessSessionImpl.Insert(Object entity) in C:\Projects\Private\nhibernate-core\src\NHibernate\Impl\StatelessSessionImpl.cs:line 467
   at NHibernate.Test.NHSpecificTest.GH2908.ByCodeFixture.ShouldBeAbleToSaveGroup() in C:\Projects\Private\nhibernate-core\src\NHibernate.Test\NHSpecificTest\GH2908\FixtureByCode.cs:line 47
--InvalidCastException
   at (Object )
   at NHibernate.Bytecode.Lightweight.AccessOptimizer.GetSpecializedPropertyValue(Object target) in C:\Projects\Private\nhibernate-core\src\NHibernate\Bytecode\Lightweight\AccessOptimizer.cs:line 81
   at NHibernate.Bytecode.AccessOptimizerExtensions.GetSpecializedPropertyValue(IAccessOptimizer optimizer, Object target) in C:\Projects\Private\nhibernate-core\src\NHibernate\Bytecode\IAccessOptimizer.cs:line 54
   at NHibernate.Tuple.Entity.PocoEntityTuplizer.GetIdentifierPropertyValue(Object entity) in C:\Projects\Private\nhibernate-core\src\NHibernate\Tuple\Entity\PocoEntityTuplizer.cs:line 365
   at NHibernate.Tuple.Entity.AbstractEntityTuplizer.GetIdentifier(Object entity) in C:\Projects\Private\nhibernate-core\src\NHibernate\Tuple\Entity\AbstractEntityTuplizer.cs:line 141
   at NHibernate.Persister.Entity.AbstractEntityPersister.GetIdentifier(Object obj) in C:\Projects\Private\nhibernate-core\src\NHibernate\Persister\Entity\AbstractEntityPersister.cs:line 4475
   at NHibernate.Persister.Entity.AbstractEntityPersister.IsTransient(Object entity, ISessionImplementor session) in C:\Projects\Private\nhibernate-core\src\NHibernate\Persister\Entity\AbstractEntityPersister.cs:line 4248
   at NHibernate.Engine.ForeignKeys.IsTransientFast(String entityName, Object entity, ISessionImplementor session) in C:\Projects\Private\nhibernate-core\src\NHibernate\Engine\ForeignKeys.cs:line 193
   at NHibernate.Engine.ForeignKeys.GetEntityIdentifierIfNotUnsaved(String entityName, Object entity, ISessionImplementor session) in C:\Projects\Private\nhibernate-core\src\NHibernate\Engine\ForeignKeys.cs:line 265
   at NHibernate.Type.EntityType.GetReferenceValue(Object value, ISessionImplementor session) in C:\Projects\Private\nhibernate-core\src\NHibernate\Type\EntityType.cs:line 168
   at NHibernate.Type.ManyToOneType.NullSafeSet(DbCommand st, Object value, Int32 index, Boolean[] settable, ISessionImplementor session) in C:\Projects\Private\nhibernate-core\src\NHibernate\Type\ManyToOneType.cs:line 60
   at NHibernate.Persister.Entity.AbstractEntityPersister.Dehydrate(Object id, Object[] fields, Object rowId, Boolean[] includeProperty, Boolean[][] includeColumns, Int32 table, DbCommand statement, ISessionImplementor session, Int32 index) in C:\Projects\Private\nhibernate-core\src\NHibernate\Persister\Entity\AbstractEntityPersister.cs:line 2798
```

**Comment by hazzik** [comment]
Seems like regression of #2056

**Comment by hazzik** [comment]
But as @bahusoid has predicted, this is incorrect mapping. The fix would be to change group mapping to following:

```
ManyToOne(x => x.Leader, map =>
{
    map.NotNullable(false);
    map.Column("`Person`");
	map.Class(typeof(Person));
    //map.Class(typeof(Programmer));
    //map.Class(typeof(Manager));
});
```
And make `Person` implement `IPerson`.

**Comment by andrejkudinov** [comment]
@bahusoid, @hazzik, thanks for the analysis.
