### ISSUE TITLE
NHibernate.Envers and ProxyForFieldInterceptor

### ISSUE THREAD

**Issue by NikitaEgorov** [nhibernate/nhibernate-core#2913]
Envers has code that cast object to `INHibernateProxy `
```C#
private static object getIdentifier(ISessionImplementor session, object obj)
{
	return obj == null
		? null
		: (obj is INHibernateProxy objAsProxy
			? objAsProxy.HibernateLazyInitializer.Identifier
			: session.GetEntityPersister(null, obj).GetIdentifier(obj));
}
```

Now I have some trouble with object saving.

I get some object with lazy reference from DB
And NHibernate set Lazy property as CantonProxyForFieldInterceptor 
Next I create new Object and get Canton from DB using session.Query<Canton>.Where(x=>x.Id=1)
And Nhibernate return CantonProxyForFieldInterceptor.
This thing completely kill Envers :(

**Comment by NikitaEgorov** [comment]
Exception from Envers
```
NHibernate.MappingException: No persister for: CantonProxyForFieldInterceptor
   at NHibernate.Impl.SessionFactoryImpl.GetEntityPersister(String entityName)
   at NHibernate.Impl.SessionImpl.GetEntityPersister(String entityName, Object obj)
   at NHibernate.Envers.Tools.Toolz.getIdentifier(ISessionImplementor session, Object obj)
   at NHibernate.Envers.Tools.Toolz.EntitiesEqual(ISessionImplementor session, Object obj1, Object obj2)
   at NHibernate.Envers.Entities.Mapper.Relation.ToOneIdMapper.MapToMapFromEntity(ISessionImplementor session, IDictionary`2 data, Object newObj, Object oldObj)
   at NHibernate.Envers.Entities.Mapper.MultiPropertyMapper.Map(ISessionImplementor session, IDictionary`2 data, String[] propertyNames, Object[] newState, Object[] oldState)
   at NHibernate.Envers.Synchronization.Work.AddWorkUnit..ctor(ISessionImplementor sessionImplementor, String entityName, AuditConfiguration verCfg, Object id, IEntityPersister entityPersister, Object[] state)
   at NHibernate.Envers.Event.AuditEventListener.OnPostInsert(PostInsertEvent evt)
   at NHibernate.Action.EntityInsertAction.PostInsert()
   at NHibernate.Action.EntityInsertAction.Execute()
   at NHibernate.Engine.ActionQueue.InnerExecute(IExecutable executable)
   at NHibernate.Engine.ActionQueue.ExecuteActions[T](List`1 list)
   at NHibernate.Engine.ActionQueue.ExecuteActions()
   at NHibernate.Event.Default.AbstractFlushingEventListener.PerformExecutions(IEventSource session)
   at NHibernate.Event.Default.DefaultFlushEventListener.OnFlush(FlushEvent event)
   at NHibernate.Impl.SessionImpl.Flush()
```

**Comment by bahusoid** [comment]
Looks related to #2727

**Comment by bahusoid** [comment]
So a local fix would be using `BestGuessEntityName` in Envers `getIdentifier`:
```C#
private static object getIdentifier(ISessionImplementor session, object obj)
{
	return obj == null
		? null
		: (obj is INHibernateProxy objAsProxy
			? objAsProxy.HibernateLazyInitializer.Identifier
			: session.GetEntityPersister(session.BestGuessEntityName(obj), obj).GetIdentifier(obj));
}
```

**Comment by RogerKratz** [comment]
@bahusoid thanks, fixed (in envers)

**Comment by NikitaEgorov** [comment]
Thanks to all
