### ISSUE TITLE
Fetching a lazy loaded component regression

### ISSUE THREAD

**Issue by nfplee** [nhibernate/nhibernate-core#3164]
I have identified a regression introduced in version 5.3.0. It happens when trying to fetch a lazy loaded component which has a read-only property and is mapped as an interface.

It's a little querky to explain but I've tried to produce a minimal sample to show you the issue.

Please see the attached application (making sure to set the connection string). The database must have the following structure:

```
CREATE TABLE [dbo].[ContentItems](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](100) NOT NULL,
	[PageTitle] [nvarchar](1024) NULL
)
```

[Test NHibernate.zip](https://github.com/nhibernate/nhibernate-core/files/9644422/Test.NHibernate.zip)

**Comment by bahusoid** [comment]
You should provide exception stacktrace and problematic query in issue description to make it more clear.

Also please use https://github.com/nhibernate/nhibernate-core-testcase for providing reproduction solutions in future (see GH0000 folder with test templates)

Ok.  I executed your solution and everything seems to work OK for me with my connection string (at least no exceptions) using 5.3.0 and 5.3.13

**Comment by bahusoid** [comment]
I uncommented   `ThenFetch(h => h.Title)` and now it throws in 5.3:

```C#
System.InvalidOperationException: Property Head.Title does not exist on entity ConsoleApp1.Models.ContentItem
   at NHibernate.Persister.Entity.AbstractEntityPersister.PropertySelectFragment(String name, String suffix, ICollection`1 fetchProperties, Boolean allProperties)
   at NHibernate.Hql.Ast.ANTLR.Tree.SelectClause.RenderNonScalarProperties(ASTAppender appender, FromElement fromElement, Int32 nonscalarSize, Int32 k)
   at NHibernate.Hql.Ast.ANTLR.Tree.SelectClause.RenderNonScalarSelects(ISelectExpression[] selectExpressions, FromClause currentFromClause)
   at NHibernate.Hql.Ast.ANTLR.Tree.SelectClause.InitializeExplicitSelectClause(FromClause fromClause)
   at NHibernate.Hql.Ast.ANTLR.HqlSqlWalker.ProcessQuery(IASTNode select, IASTNode query)
   at NHibernate.Hql.Ast.ANTLR.HqlSqlWalker.unionedQuery()
   at NHibernate.Hql.Ast.ANTLR.HqlSqlWalker.query()
   at NHibernate.Hql.Ast.ANTLR.HqlSqlWalker.selectStatement()
   at NHibernate.Hql.Ast.ANTLR.HqlSqlWalker.statement()
   at NHibernate.Hql.Ast.ANTLR.HqlSqlWalker.Transform()
   at NHibernate.Hql.Ast.ANTLR.HqlSqlTranslator.Translate()
   at NHibernate.Hql.Ast.ANTLR.QueryTranslatorImpl.Analyze(String collectionRole)
   at NHibernate.Hql.Ast.ANTLR.QueryTranslatorImpl.DoCompile(IDictionary`2 replacements, Boolean shallow, String collectionRole)
   at NHibernate.Hql.Ast.ANTLR.ASTQueryTranslatorFactory.CreateQueryTranslators(IQueryExpression queryExpression, IASTNode ast, String queryIdentifier, String collectionRole, Boolean shallow, IDictionary`2 filters, ISessionFactoryImplementor factory)
   at NHibernate.Hql.Ast.ANTLR.ASTQueryTranslatorFactory.CreateQueryTranslators(IQueryExpression queryExpression, String collectionRole, Boolean shallow, IDictionary`2 filters, ISessionFactoryImplementor factory)
   at NHibernate.Engine.Query.QueryExpressionPlan.CreateTranslators(IQueryExpression queryExpression, String collectionRole, Boolean shallow, IDictionary`2 enabledFilters, ISessionFactoryImplementor factory)
   at NHibernate.Engine.Query.QueryExpressionPlan..ctor(IQueryExpression queryExpression, Boolean shallow, IDictionary`2 enabledFilters, ISessionFactoryImplementor factory)
   at NHibernate.Engine.Query.QueryPlanCache.GetHQLQueryPlan(IQueryExpression queryExpression, Boolean shallow, IDictionary`2 enabledFilters)
   at NHibernate.Impl.AbstractSessionImpl.GetHQLQueryPlan(IQueryExpression queryExpression, Boolean shallow)
   at NHibernate.Impl.AbstractSessionImpl.CreateQuery(IQueryExpression queryExpression)
   at NHibernate.Linq.DefaultQueryProvider.PrepareQuery(Expression expression, IQuery& query)
   at NHibernate.Linq.DefaultQueryProvider.ExecuteListAsync[TResult](Expression expression, CancellationToken cancellationToken)
```

But it doesn't work in 5.2.7 either (different exception though)
```C#
NHibernate.Hql.Ast.ANTLR.InvalidPathException: Invalid join: _0.Title [.ThenFetch[ConsoleApp1.Models.ContentItem, ConsoleApp1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null,ConsoleApp1.Models.IHead, ConsoleApp1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null,System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e](.Fetch[ConsoleApp1.Models.ContentItem, ConsoleApp1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null,ConsoleApp1.Models.IHead, ConsoleApp1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null](NHibernate.Linq.NhQueryable`1[ConsoleApp1.Models.ContentItem], Quote((i, ) => (i.Head)), ), Quote((h, ) => (h.Title)), )]
   at NHibernate.Hql.Ast.ANTLR.HqlSqlWalker.CreateFromJoinElement(IASTNode path, IASTNode alias, Int32 joinType, IASTNode fetchNode, IASTNode propertyFetch, IASTNode with)
   at NHibernate.Hql.Ast.ANTLR.HqlSqlWalker.joinElement()
   at NHibernate.Hql.Ast.ANTLR.HqlSqlWalker.fromElement()
   at NHibernate.Hql.Ast.ANTLR.HqlSqlWalker.fromElementList()
   at NHibernate.Hql.Ast.ANTLR.HqlSqlWalker.fromClause()
   at NHibernate.Hql.Ast.ANTLR.HqlSqlWalker.unionedQuery()
   at NHibernate.Hql.Ast.ANTLR.HqlSqlWalker.query()
   at NHibernate.Hql.Ast.ANTLR.HqlSqlWalker.selectStatement()
   at NHibernate.Hql.Ast.ANTLR.HqlSqlWalker.statement()
   at NHibernate.Hql.Ast.ANTLR.HqlSqlTranslator.Translate()
   at NHibernate.Hql.Ast.ANTLR.QueryTranslatorImpl.Analyze(String collectionRole)
   at NHibernate.Hql.Ast.ANTLR.QueryTranslatorImpl.DoCompile(IDictionary`2 replacements, Boolean shallow, String collectionRole)
   at NHibernate.Hql.Ast.ANTLR.ASTQueryTranslatorFactory.CreateQueryTranslators(IASTNode ast, String queryIdentifier, String collectionRole, Boolean shallow, IDictionary`2 filters, ISessionFactoryImplementor factory)
   at NHibernate.Hql.Ast.ANTLR.ASTQueryTranslatorFactory.CreateQueryTranslators(IQueryExpression queryExpression, String collectionRole, Boolean shallow, IDictionary`2 filters, ISessionFactoryImplementor factory)
   at NHibernate.Engine.Query.QueryExpressionPlan.CreateTranslators(IQueryExpression queryExpression, String collectionRole, Boolean shallow, IDictionary`2 enabledFilters, ISessionFactoryImplementor factory)
   at NHibernate.Engine.Query.QueryExpressionPlan..ctor(IQueryExpression queryExpression, Boolean shallow, IDictionary`2 enabledFilters, ISessionFactoryImplementor factory)
   at NHibernate.Engine.Query.QueryPlanCache.GetHQLQueryPlan(IQueryExpression queryExpression, Boolean shallow, IDictionary`2 enabledFilters)
   at NHibernate.Impl.AbstractSessionImpl.GetHQLQueryPlan(IQueryExpression queryExpression, Boolean shallow)
   at NHibernate.Impl.AbstractSessionImpl.CreateQuery(IQueryExpression queryExpression)
   at NHibernate.Linq.DefaultQueryProvider.PrepareQuery(Expression expression, IQuery& query)
   at NHibernate.Linq.DefaultQueryProvider.ExecuteAsync(Expression expression, CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at NHibernate.Linq.DefaultQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
```

So please clarify what regression are you talking about?

**Comment by nfplee** [comment]
Thanks for the link in producing a test case. I'm not interested in the ThenFetch part, that was just me experimenting as I'm going to Lazy load the entire component,

**Comment by nfplee** [comment]
@bahusoid sorry I mis-read your reply as I was at a funeral. I can't work out why you can't reproduce this. Please note the error I'm getting is:

> IndexOutOfRangeException: formula0_

I am using MS SQL Server as I couldn't reproduce the error using SQLite.

I'm currently working on a test case.

**Comment by bahusoid** [comment]
Ok. Waiting for failed test.

Regarding your mappings:
```C#
Property(x => x.DummyFieldToLoadEmptyComponent, m =>
{
	m.Access(Accessor.ReadOnly);
	m.Formula("1");
});
```

Readonly access means that property is not used for entity loading:
```
readonly - Access the mapped property through a Property get to get the value and do nothing to set the value. This is useful to allow calculated properties in the domain that will never be recovered from the DB but can be used for querying.
```
So it shouldn't affect Fetch in any way.

**Comment by nfplee** [comment]
Yeah I literally removed my connection string and zipped it up. I'm struggling to produce my test case as it keeps on passing. Is there a way to target a particular database/dialect?

Thanks for the additional information regarding read-only. Ideally I wouldn't need this property but I can't see how else I can force NHibernate not to make the component nullable (since when all properties of the component are null then the component is null). One idea is to change the head property to:

```cs
private IHead _head;
public virtual IHead Head {
    get => _head ??= new Head();
    set => _head = value;
}
```

But this requires access to the concrete class which unfortunately I don't have because of the way my application is abstracted.

**Comment by bahusoid** [comment]
Maybe it's a data specific issue. As I'm running it on empty database. And it looks like you have some data in you SQL Server database where issue is reproducible and fails to reproduce on empty SQLite database too.

**Comment by nfplee** [comment]
Thanks @bahusoid, I hadn't expected the data to cause a problem. As you discovered the issue doesn't happen with an empty table. However if you populate one record inside it then hopefully you should see the problem.

I'm still unable to re-produce a test case for this. Here's what I have come up with so far.

[GH3164.zip](https://github.com/nhibernate/nhibernate-core/files/9654977/GH3164.zip)

Thanks again for your help so far.

**Comment by bahusoid** [comment]
> No. Seems it's not as simple as that.

Ignore it. I reproduced it.

**Comment by nfplee** [comment]
Thanks, I'm glad you can reproduce.

> Also you don't need to rewrite existing mappings. Instead of writing mapper.Class<Entity> ...) you can reuse existing mapping class via mapper.AddMapping<ContentItemMapping>() or mapper.AddMapping<HeadMapping>()

Yeah I know but I found it easier to modify if it was all within 1 file.

**Comment by bahusoid** [comment]
Test case https://github.com/bahusoid/nhibernate-core/tree/gh3164. Not sure but seems regression from https://github.com/nhibernate/nhibernate-core/pull/1922

**Comment by bahusoid** [comment]
Fixed by #3171

**Comment by nfplee** [comment]
Great, thanks @bahusoid.
