### ISSUE TITLE
NHibernate.Exceptions.GenericADOException: could not load an entity-->System.IndexOutOfRangeException: clazz_0_ at System.Data.ProviderBase.FieldNameLookup.GetOrdinal(String fieldName) at System.Data.SqlClient.SqlDataReader.GetOrdinal(String name) at NHibernate.Type.NullableType.NullSafeGet(IDataReader rs, String name) 

### ISSUE THREAD

**Issue by lalitjamwal37012** [nhibernate/nhibernate-core#3200]
Hi Team,

Currently we are facing an issue with Nhibernate, we are getting intermittent `System.IndexOutOfRangeException` errors on Live env.
When we see multiple occurrences(more than 500) then application stops working and we need to restart the IIS to up the application again.
Please find the below details and let us know in case you need any additional details:

NHibernate version: 
Product Name : NHibernate
File Version: 3.2.0.4000
Product Version: 3.2.0.4000

Main exception:
```
System.IndexOutOfRangeException: clazz_0_
   at System.Data.ProviderBase.FieldNameLookup.GetOrdinal(String fieldName)
   at System.Data.SqlClient.SqlDataReader.GetOrdinal(String name)
   at NHibernate.Type.NullableType.NullSafeGet(IDataReader rs, String name) in D:\Marko\Code\nhibernate-3.2.0-src\src\NHibernate\Type\NullableType.cs:line 236
```

Error Logs:
```
2022-11-15 08:16:22,505 [94] FATAL UnderwritingPlatform.Core.Service.UserManager [(null)] - Exception encountered attempting to retrieve user by id >2531665092<
NHibernate.Exceptions.GenericADOException: could not load an entity: [UnderwritingPlatform.Core.Domain.Person#2392365568][SQL: SELECT person0_.PersonId as PartyId197_0_, person0_1_.GlobalNameId as GlobalNa2_197_0_, person0_2_.LicenseNumber as LicenseN2_199_0_, person0_2_.SignatureImageId as Signatur3_199_0_, person0_4_.LicenseNumber as LicenseN2_201_0_, person0_4_.SignatureImageId as Signatur3_201_0_, case when person0_2_.UnderwriterId is not null then 2 when person0_3_.BrokerContactId is not null then 3 when person0_4_.AssistantId is not null then 4 when person0_5_.CSId is not null then 5 when person0_6_.ActuaryId is not null then 6 when person0_7_.ClaimsAdminContactId is not null then 7 when person0_8_.Id is not null then 8 when person0_.PersonId is not null then 1 end as clazz_0_ FROM Person person0_ inner join Party person0_1_ on person0_.PersonId=person0_1_.PartyId left outer join Underwriter person0_2_ on person0_.PersonId=person0_2_.UnderwriterId left outer join BrokerContact person0_3_ on person0_.PersonId=person0_3_.BrokerContactId left outer join Assistant person0_4_ on person0_.PersonId=person0_4_.AssistantId left outer join CSUser person0_5_ on person0_.PersonId=person0_5_.CSId left outer join Actuary person0_6_ on person0_.PersonId=person0_6_.ActuaryId left outer join ClaimsAdminContact person0_7_ on person0_.PersonId=person0_7_.ClaimsAdminContactId left outer join AuditUser person0_8_ on person0_.PersonId=person0_8_.Id WHERE person0_.PersonId=?] ---> System.IndexOutOfRangeException: clazz_0_
   at System.Data.ProviderBase.FieldNameLookup.GetOrdinal(String fieldName)
   at System.Data.SqlClient.SqlDataReader.GetOrdinal(String name)
   at NHibernate.Type.NullableType.NullSafeGet(IDataReader rs, String name) in D:\Marko\Code\nhibernate-3.2.0-src\src\NHibernate\Type\NullableType.cs:line 236
   at NHibernate.Loader.Loader.GetInstanceClass(IDataReader rs, Int32 i, ILoadable persister, Object id, ISessionImplementor session) in D:\Marko\Code\nhibernate-3.2.0-src\src\NHibernate\Loader\Loader.cs:line 1024
   at NHibernate.Loader.Loader.InstanceNotYetLoaded(IDataReader dr, Int32 i, ILoadable persister, EntityKey key, LockMode lockMode, String rowIdAlias, EntityKey optionalObjectKey, Object optionalObject, IList hydratedObjects, ISessionImplementor session) in D:\Marko\Code\nhibernate-3.2.0-src\src\NHibernate\Loader\Loader.cs:line 925
   at NHibernate.Loader.Loader.GetRow(IDataReader rs, ILoadable[] persisters, EntityKey[] keys, Object optionalObject, EntityKey optionalObjectKey, LockMode[] lockModes, IList hydratedObjects, ISessionImplementor session) in D:\Marko\Code\nhibernate-3.2.0-src\src\NHibernate\Loader\Loader.cs:line 875
   at NHibernate.Loader.Loader.GetRowFromResultSet(IDataReader resultSet, ISessionImplementor session, QueryParameters queryParameters, LockMode[] lockModeArray, EntityKey optionalObjectKey, IList hydratedObjects, EntityKey[] keys, Boolean returnProxies) in D:\Marko\Code\nhibernate-3.2.0-src\src\NHibernate\Loader\Loader.cs:line 341
   at NHibernate.Loader.Loader.DoQuery(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies) in D:\Marko\Code\nhibernate-3.2.0-src\src\NHibernate\Loader\Loader.cs:line 468
   at NHibernate.Loader.Loader.DoQueryAndInitializeNonLazyCollections(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies) in D:\Marko\Code\nhibernate-3.2.0-src\src\NHibernate\Loader\Loader.cs:line 246
   at NHibernate.Loader.Loader.LoadEntity(ISessionImplementor session, Object id, IType identifierType, Object optionalObject, String optionalEntityName, Object optionalIdentifier, IEntityPersister persister) in D:\Marko\Code\nhibernate-3.2.0-src\src\NHibernate\Loader\Loader.cs:line 1300
   --- End of inner exception stack trace ---
   at NHibernate.Loader.Loader.LoadEntity(ISessionImplementor session, Object id, IType identifierType, Object optionalObject, String optionalEntityName, Object optionalIdentifier, IEntityPersister persister) in D:\Marko\Code\nhibernate-3.2.0-src\src\NHibernate\Loader\Loader.cs:line 1288
   at NHibernate.Loader.Entity.AbstractEntityLoader.Load(ISessionImplementor session, Object id, Object optionalObject, Object optionalId) in D:\Marko\Code\nhibernate-3.2.0-src\src\NHibernate\Loader\Entity\AbstractEntityLoader.cs:line 44
   at NHibernate.Loader.Entity.AbstractEntityLoader.Load(Object id, Object optionalObject, ISessionImplementor session) in D:\Marko\Code\nhibernate-3.2.0-src\src\NHibernate\Loader\Entity\AbstractEntityLoader.cs:line 39
   at NHibernate.Event.Default.DefaultLoadEventListener.LoadFromDatasource(LoadEvent event, IEntityPersister persister, EntityKey keyToLoad, LoadType options) in D:\Marko\Code\nhibernate-3.2.0-src\src\NHibernate\Event\Default\DefaultLoadEventListener.cs:line 348
   at NHibernate.Event.Default.DefaultLoadEventListener.Load(LoadEvent event, IEntityPersister persister, EntityKey keyToLoad, LoadType options) in D:\Marko\Code\nhibernate-3.2.0-src\src\NHibernate\Event\Default\DefaultLoadEventListener.cs:line 110
   at NHibernate.Event.Default.DefaultLoadEventListener.OnLoad(LoadEvent event, LoadType loadType) in D:\Marko\Code\nhibernate-3.2.0-src\src\NHibernate\Event\Default\DefaultLoadEventListener.cs:line 93
   at NHibernate.Impl.SessionImpl.FireLoad(LoadEvent event, LoadType loadType) in D:\Marko\Code\nhibernate-3.2.0-src\src\NHibernate\Impl\SessionImpl.cs:line 2502
   at NHibernate.Impl.SessionImpl.InternalLoad(String entityName, Object id, Boolean eager, Boolean isNullable) in D:\Marko\Code\nhibernate-3.2.0-src\src\NHibernate\Impl\SessionImpl.cs:line 1393
   at NHibernate.Type.EntityType.ResolveIdentifier(Object id, ISessionImplementor session) in D:\Marko\Code\nhibernate-3.2.0-src\src\NHibernate\Type\EntityType.cs:line 397
   at NHibernate.Engine.TwoPhaseLoad.InitializeEntity(Object entity, Boolean readOnly, ISessionImplementor session, PreLoadEvent preLoadEvent, PostLoadEvent postLoadEvent) in D:\Marko\Code\nhibernate-3.2.0-src\src\NHibernate\Engine\TwoPhaseLoad.cs:line 79
   at NHibernate.Loader.Loader.InitializeEntitiesAndCollections(IList hydratedObjects, Object resultSetId, ISessionImplementor session, Boolean readOnly) in D:\Marko\Code\nhibernate-3.2.0-src\src\NHibernate\Loader\Loader.cs:line 598
   at NHibernate.Loader.Loader.DoQuery(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies) in D:\Marko\Code\nhibernate-3.2.0-src\src\NHibernate\Loader\Loader.cs:line 477
   at NHibernate.Loader.Loader.DoQueryAndInitializeNonLazyCollections(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies) in D:\Marko\Code\nhibernate-3.2.0-src\src\NHibernate\Loader\Loader.cs:line 246
   at NHibernate.Loader.Loader.LoadEntity(ISessionImplementor session, Object id, IType identifierType, Object optionalObject, String optionalEntityName, Object optionalIdentifier, IEntityPersister persister) in D:\Marko\Code\nhibernate-3.2.0-src\src\NHibernate\Loader\Loader.cs:line 1304
   at NHibernate.Loader.Entity.AbstractEntityLoader.Load(ISessionImplementor session, Object id, Object optionalObject, Object optionalId) in D:\Marko\Code\nhibernate-3.2.0-src\src\NHibernate\Loader\Entity\AbstractEntityLoader.cs:line 44
   at NHibernate.Loader.Entity.AbstractEntityLoader.Load(Object id, Object optionalObject, ISessionImplementor session) in D:\Marko\Code\nhibernate-3.2.0-src\src\NHibernate\Loader\Entity\AbstractEntityLoader.cs:line 39
   at NHibernate.Event.Default.DefaultLoadEventListener.LoadFromDatasource(LoadEvent event, IEntityPersister persister, EntityKey keyToLoad, LoadType options) in D:\Marko\Code\nhibernate-3.2.0-src\src\NHibernate\Event\Default\DefaultLoadEventListener.cs:line 348
   at NHibernate.Event.Default.DefaultLoadEventListener.Load(LoadEvent event, IEntityPersister persister, EntityKey keyToLoad, LoadType options) in D:\Marko\Code\nhibernate-3.2.0-src\src\NHibernate\Event\Default\DefaultLoadEventListener.cs:line 110
   at NHibernate.Event.Default.DefaultLoadEventListener.OnLoad(LoadEvent event, LoadType loadType) in D:\Marko\Code\nhibernate-3.2.0-src\src\NHibernate\Event\Default\DefaultLoadEventListener.cs:line 93
   at NHibernate.Impl.SessionImpl.FireLoad(LoadEvent event, LoadType loadType) in D:\Marko\Code\nhibernate-3.2.0-src\src\NHibernate\Impl\SessionImpl.cs:line 2502
   at NHibernate.Impl.SessionImpl.Get(String entityName, Object id) in D:\Marko\Code\nhibernate-3.2.0-src\src\NHibernate\Impl\SessionImpl.cs:line 1347
   at NHibernate.Impl.SessionImpl.Get(Type entityClass, Object id) in D:\Marko\Code\nhibernate-3.2.0-src\src\NHibernate\Impl\SessionImpl.cs:line 1283
   at NHibernate.Impl.SessionImpl.Get[T](Object id) in D:\Marko\Code\nhibernate-3.2.0-src\src\NHibernate\Impl\SessionImpl.cs:line 1267
   at UnderwritingPlatform.Core.Service.UserManager.FindUser(Int64 aUserId) in D:\agent1\_work\488\s\Core.UnderwritingPlatform\Service\UserManager.cs:line 314

2022-11-15 08:16:22,684 [94] FATAL UnderwritingPlatform.Ui.Global [(null)] - GUID: [{1f6139a7-1aed-4260-9a7e-400f28bbe75d}] UserId: [2531665092] QueryString: []
System.IndexOutOfRangeException: clazz_0_
   at System.Data.ProviderBase.FieldNameLookup.GetOrdinal(String fieldName)
   at System.Data.SqlClient.SqlDataReader.GetOrdinal(String name)
   at NHibernate.Type.NullableType.NullSafeGet(IDataReader rs, String name) in D:\Marko\Code\nhibernate-3.2.0-src\src\NHibernate\Type\NullableType.cs:line 236
   at NHibernate.Loader.Loader.GetInstanceClass(IDataReader rs, Int32 i, ILoadable persister, Object id, ISessionImplementor session) in D:\Marko\Code\nhibernate-3.2.0-src\src\NHibernate\Loader\Loader.cs:line 1024
   at NHibernate.Loader.Loader.InstanceNotYetLoaded(IDataReader dr, Int32 i, ILoadable persister, EntityKey key, LockMode lockMode, String rowIdAlias, EntityKey optionalObjectKey, Object optionalObject, IList hydratedObjects, ISessionImplementor session) in D:\Marko\Code\nhibernate-3.2.0-src\src\NHibernate\Loader\Loader.cs:line 925
   at NHibernate.Loader.Loader.GetRow(IDataReader rs, ILoadable[] persisters, EntityKey[] keys, Object optionalObject, EntityKey optionalObjectKey, LockMode[] lockModes, IList hydratedObjects, ISessionImplementor session) in D:\Marko\Code\nhibernate-3.2.0-src\src\NHibernate\Loader\Loader.cs:line 875
   at NHibernate.Loader.Loader.GetRowFromResultSet(IDataReader resultSet, ISessionImplementor session, QueryParameters queryParameters, LockMode[] lockModeArray, EntityKey optionalObjectKey, IList hydratedObjects, EntityKey[] keys, Boolean returnProxies) in D:\Marko\Code\nhibernate-3.2.0-src\src\NHibernate\Loader\Loader.cs:line 341
   at NHibernate.Loader.Loader.DoQuery(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies) in D:\Marko\Code\nhibernate-3.2.0-src\src\NHibernate\Loader\Loader.cs:line 468
   at NHibernate.Loader.Loader.DoQueryAndInitializeNonLazyCollections(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies) in D:\Marko\Code\nhibernate-3.2.0-src\src\NHibernate\Loader\Loader.cs:line 246
   at NHibernate.Loader.Loader.LoadEntity(ISessionImplementor session, Object id, IType identifierType, Object optionalObject, String optionalEntityName, Object optionalIdentifier, IEntityPersister persister) in D:\Marko\Code\nhibernate-3.2.0-src\src\NHibernate\Loader\Loader.cs:line 1300

2022-11-15 08:16:22,426 [12] FATAL UnderwritingPlatform.Ui.Global [(null)] - GUID: [{a6ca2b4f-8868-48d3-a125-f335da3672fc}] UserId: [2392393969] QueryString: []
System.IndexOutOfRangeException: UserPers1_239_0_
   at System.Data.ProviderBase.FieldNameLookup.GetOrdinal(String fieldName)
   at System.Data.SqlClient.SqlDataReader.GetOrdinal(String name)
   at NHibernate.Type.NullableType.NullSafeGet(IDataReader rs, String name) in D:\Marko\Code\nhibernate-3.2.0-src\src\NHibernate\Type\NullableType.cs:line 236
   at NHibernate.Loader.Loader.GetKeyFromResultSet(Int32 i, IEntityPersister persister, Object id, IDataReader rs, ISessionImplementor session) in D:\Marko\Code\nhibernate-3.2.0-src\src\NHibernate\Loader\Loader.cs:line 790
   at NHibernate.Loader.Loader.GetRowFromResultSet(IDataReader resultSet, ISessionImplementor session, QueryParameters queryParameters, LockMode[] lockModeArray, EntityKey optionalObjectKey, IList hydratedObjects, EntityKey[] keys, Boolean returnProxies) in D:\Marko\Code\nhibernate-3.2.0-src\src\NHibernate\Loader\Loader.cs:line 324
   at NHibernate.Loader.Loader.DoQuery(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies) in D:\Marko\Code\nhibernate-3.2.0-src\src\NHibernate\Loader\Loader.cs:line 468
   at NHibernate.Loader.Loader.DoQueryAndInitializeNonLazyCollections(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies) in D:\Marko\Code\nhibernate-3.2.0-src\src\NHibernate\Loader\Loader.cs:line 246
   at NHibernate.Loader.Loader.LoadEntity(ISessionImplementor session, Object id, IType identifierType, Object optionalObject, String optionalEntityName, Object optionalIdentifier, IEntityPersister persister) in D:\Marko\Code\nhibernate-3.2.0-src\src\NHibernate\Loader\Loader.cs:line 1300
```

**Comment by fredericDelaporte** [comment]
We do not patch NHibernate 3 anymore (neither 4). It is likely you will be mostly on your own for solving this issue if you stay on such an old release.
