### ISSUE TITLE
JoinAlias to "string collection" property - the where clause is not generated properly

### ISSUE THREAD

**Issue by xhafan** [nhibernate/nhibernate-core#3235]
I have entity `Destination` with a "string collection" property `ActivationCodes`:
```C#
public class Destination
{
    private readonly ISet<string> _activationCodes = new HashSet<string>();
...
    public virtual IEnumerable<string> ActivationCodes => _activationCodes;
```
This is my FluentNHibernate mapping:
```C#
public class DestinationMappingOverrides : IAutoMappingOverride<Destination>
{
    public void Override(AutoMapping<Destination> mapping)
    {
        mapping.HasMany(x => x.ActivationCodes)
            .Table("DestinationActivationCode")
            .Element("Value", x => x.Not.Nullable());
    }            
```
This is generated `hbm.xml`:
```XML
...
    <set access="nosetter.camelcase-underscore" cascade="all-delete-orphan" name="ActivationCodes" table="DestinationActivationCode">
      <key>
        <column name="DestinationId" />
      </key>
      <element type="System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e">
        <column name="Value" not-null="true" />
      </element>
    </set>
...
```
This is my QueryOver:
```C#
Destination destinationAlias = null!;
string activationCodeAlias = null!;

var activationCodes = new List<string> { "code1", "code2" };

var queryOver = Session.QueryOver(() => destinationAlias)
    .JoinAlias(x => x.ActivationCodes, () => activationCodeAlias)
    .Where(() => activationCodeAlias.IsIn(activationCodes))
```
It generates the following SQL:
```SQL
SELECT
...
FROM "Destination" this_ 
join "DestinationActivationCode" activation1_ on this_."Id"=activation1_."DestinationId" 
WHERE  NULL /* :p1 */ in (
   'code1' /* :p2 */,
   'code2' /* :p3 */
)
```
Please note the `NULL` -> it should generate `activation1_."Value"` instead of `NULL`. I could create a sample github repository if needed to demonstrate the issue. 

Tested on .NET 6, NHibernate 5.3.12 and 5.4.1

**Comment by bahusoid** [comment]
Does it work with `Restrictions.In`?
```C#
.Where(Restrictions.In(nameof(activationCodeAlias), activationCodes ))
```

**Comment by xhafan** [comment]
It does not work, `.Where(Restrictions.In(nameof(activationCodeAlias), activationCodes))` gives me:
```C#
NHibernate.QueryException : Could not find property activationCodeAlias
   at NHibernate.Loader.Criteria.CriteriaQueryTranslator.GetTypeUsingProjection(ICriteria subcriteria, String propertyName)
   at NHibernate.Criterion.InExpression.AssertPropertyIsNotCollection(ICriteriaQuery criteriaQuery, ICriteria criteria)
   at NHibernate.Criterion.InExpression.ToSqlString(ICriteria criteria, ICriteriaQuery criteriaQuery)
   at NHibernate.Loader.Criteria.CriteriaQueryTranslator.GetWhereCondition()
   at NHibernate.Loader.Criteria.CriteriaJoinWalker..ctor(IOuterJoinLoadable persister, CriteriaQueryTranslator translator, ISessionFactoryImplementor factory, ICriteria criteria, String rootEntityName, IDictionary`2 enabledFilters)
   at NHibernate.Loader.Criteria.CriteriaLoader..ctor(IOuterJoinLoadable persister, ISessionFactoryImplementor factory, CriteriaImpl rootCriteria, String rootEntityName, IDictionary`2 enabledFilters)
   at NHibernate.Impl.SessionImpl.ListAsync[T](CriteriaImpl criteria, CancellationToken cancellationToken)
   at NHibernate.Impl.CriteriaImpl.ListAsync[T](CancellationToken cancellationToken)
   at 
```
I managed to progress further with `.Where(Restrictions.In("ActivationCodes", activationCodes))`, but got this exception:
```C#
NHibernate.QueryException : Cannot use collections with InExpression
   at NHibernate.Criterion.InExpression.AssertPropertyIsNotCollection(ICriteriaQuery criteriaQuery, ICriteria criteria)
   at NHibernate.Criterion.InExpression.ToSqlString(ICriteria criteria, ICriteriaQuery criteriaQuery)
   at NHibernate.Loader.Criteria.CriteriaQueryTranslator.GetWhereCondition()
   at NHibernate.Loader.Criteria.CriteriaJoinWalker..ctor(IOuterJoinLoadable persister, CriteriaQueryTranslator translator, ISessionFactoryImplementor factory, ICriteria criteria, String rootEntityName, IDictionary`2 enabledFilters)
   at NHibernate.Loader.Criteria.CriteriaLoader..ctor(IOuterJoinLoadable persister, ISessionFactoryImplementor factory, CriteriaImpl rootCriteria, String rootEntityName, IDictionary`2 enabledFilters)
   at NHibernate.Impl.SessionImpl.ListAsync[T](CriteriaImpl criteria, CancellationToken cancellationToken)
   at NHibernate.Impl.CriteriaImpl.ListAsync[T](CancellationToken cancellationToken)
   at 
```
I also tried `.Where(Restrictions.On(() => activationCodeAlias).IsIn(activationCodes))` which generates the `NULL` in the SQL.

**Comment by bahusoid** [comment]
Hm..  What about?
```C#
  .Where(Restrictions.In(nameof(activationCodeAlias)+".id", activationCodes))
```

**Comment by xhafan** [comment]
The DB field is named `Value`, the table does not have `id` field (the table has 2 columns - `DestinationId` and `Value`), and `.Where(Restrictions.In("ActivationCodes.Value", activationCodes))` returns `Could not find property ActivationCodes.Value`.

**Comment by bahusoid** [comment]
Did you try with "id"? "id" is a special property name in Criteria with special treatment.

**Comment by xhafan** [comment]
> Did you try with "id"? "id" is a special property name in Criteria with special treatment.

ok, tried it, and got `Could not find property activationCodeAlias.id`.

**Comment by bahusoid** [comment]
Ok last try. Element collections have special properties too. Try with `elements`

```C#
.Where(Restrictions.In(nameof(activationCodeAlias) + ".elements", activationCodes))
```

`

**Comment by xhafan** [comment]
That worked, amazing, thanks a lot! 🙏🥳
