### ISSUE TITLE
Microsoft.Data.Sqlite with latest fluentnhibernate - update of tables not working 

### ISSUE THREAD

**Issue by PriyankaChandrabose** [nhibernate/nhibernate-core#3432]
_sessionFactory = Fluently.Configure().Database(MsSqliteConfiguration.Standard.ConnectionString(c => c.Is($"data source={_dbFilePath};")).Dialect<NHibernate.Extensions.Sqlite.SqliteDialect>().Driver<NHibernate.Extensions.Sqlite.SqliteDriver>())
.Mappings(m => m.FluentMappings.AddFromAssemblyOf())
.ExposeConfiguration(BuildSchema).BuildSessionFactory();

when schema update is being called, the following exception came with or with out actual schema update

ERROR NHibernate.Tool.hbm2ddl.SchemaUpdate - could not complete schema update
System.ArgumentException: More restrictions were provided than the collection 'Tables' supports.
at Microsoft.Data.Sqlite.SqliteConnection.GetSchema(String collectionName, String[] restrictionValues)
at NHibernate.Dialect.Schema.AbstractDataBaseSchema.GetTables(String catalog, String schemaPattern, String tableNamePattern, String[] types)
at NHibernate.Dialect.Schema.SQLiteDataBaseMetaData.GetTables(String catalog, String schemaPattern, String tableNamePattern, String[] types)
at NHibernate.Tool.hbm2ddl.DatabaseMetadata.GetTableMetadata(String name, String schema, String catalog, Boolean isQuoted)
at NHibernate.Cfg.Configuration.GenerateSchemaUpdateScript(Dialect dialect, IDatabaseMetadata databaseMetadata)
at NHibernate.Tool.hbm2ddl.SchemaUpdate.Execute(Action`1 scriptAction, Boolean doUpdate)

**Comment by PriyankaChandrabose** [comment]
Any update on this issue. The schema is not getting updated and throws the above exception

**Comment by PriyankaChandrabose** [comment]
how to connect nhibernate with Microsoft.Data.Sqlite without using extensions and make schema update work
