### ISSUE TITLE
AsQueryable() throws QueryException when child collection is mapped as Components collection

### ISSUE THREAD

**Issue by andriusrazinskas** [nhibernate/nhibernate-core#3444]
I am getting QueryException when using AsQueryable on collection which is mapped as HasMany(...).Component(...)

NHibernate: 5.4.6
FluentNHibernate: 3.3.0

I have created small unit test which fails due this issue, full code can be found here: https://github.com/andriusrazinskas/NHibernate-AsQueryable-on-Components

Parent class `Store`:
```c#
public class Store
{
    public virtual int Id { get; protected set; }
    public virtual string Name { get; set; }
    public virtual IList<Product> Products { get; set; }

    public Store()
    {
        Products = new List<Product>();
    }

    public virtual void AddProduct(Product product)
    {
        product.Store = this;
        Products.Add(product);
    }
}
``` 
Child class `Product`:
```c#
public class Product
{
    public virtual int Id { get; protected set; }
    public virtual string Name { get; set; }
    public virtual double Price { get; set; }
    public virtual Store Store { get; set; }
}
``` 

Their mappings:
```c#
public class ProductMap : ClassMap<Product>
{
    public ProductMap()
    {
        Id(x => x.Id);
        Map(x => x.Name);
        Map(x => x.Price);
        References(x => x.Store);
    }
}

public class StoreMap : ClassMap<Store>
{
    public StoreMap()
    {
        Id(x => x.Id);
        Map(x => x.Name);

        HasMany(x => x.Products)
            .Cascade.All()
            .LazyLoad()
            .Component(x =>
            {
                x.Map(y => y.Name);
                x.Map(y => y.Price);
                x.ParentReference(y => y.Store);
            });
    }
}
``` 

Query which throws:
```c#
var store = session.Query<Store>().First();
var productNames = store.Products.AsQueryable().Select(p => p.Name).ToArray();
``` 

Stacktrace:
```
NHibernate.QueryException : collection of values in filter: this [.Select[NHibernate.AsQueryableOnComponent.Entities.Product, NHibernate.AsQueryableOnComponent, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null,System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e](NHibernate.Linq.NhQueryable`1[NHibernate.AsQueryableOnComponent.Entities.Product], Quote((p, ) => (p.Name)), )]
   at NHibernate.Hql.Ast.ANTLR.HqlFilterPreprocessor.AddImpliedFromToFromNode(IASTNode fromClause, String collectionRole, ISessionFactoryImplementor factory)
   at NHibernate.Hql.Ast.ANTLR.HqlFilterPreprocessor.AddImpliedFromToQuery(IASTNode ast, String collectionRole, ISessionFactoryImplementor factory)
   at NHibernate.Hql.Ast.ANTLR.HqlSqlTranslator.Translate()
   at NHibernate.Hql.Ast.ANTLR.QueryTranslatorImpl.Analyze(String collectionRole)
   at NHibernate.Hql.Ast.ANTLR.QueryTranslatorImpl.DoCompile(IDictionary`2 replacements, Boolean shallow, String collectionRole)
   at NHibernate.Hql.Ast.ANTLR.ASTQueryTranslatorFactory.CreateQueryTranslators(IQueryExpression queryExpression, IASTNode ast, String queryIdentifier, String collectionRole, Boolean shallow, IDictionary`2 filters, ISessionFactoryImplementor factory)
   at NHibernate.Hql.Ast.ANTLR.ASTQueryTranslatorFactory.CreateQueryTranslators(IQueryExpression queryExpression, String collectionRole, Boolean shallow, IDictionary`2 filters, ISessionFactoryImplementor factory)
   at NHibernate.Engine.Query.QueryExpressionPlan.CreateTranslators(IQueryExpression queryExpression, String collectionRole, Boolean shallow, IDictionary`2 enabledFilters, ISessionFactoryImplementor factory)
   at NHibernate.Engine.Query.QueryExpressionPlan..ctor(IQueryExpression queryExpression, String collectionRole, Boolean shallow, IDictionary`2 enabledFilters, ISessionFactoryImplementor factory)
   at NHibernate.Engine.Query.FilterQueryPlan..ctor(IQueryExpression queryExpression, String collectionRole, Boolean shallow, IDictionary`2 enabledFilters, ISessionFactoryImplementor factory)
   at NHibernate.Engine.Query.QueryPlanCache.GetFilterQueryPlan(IQueryExpression queryExpression, String collectionRole, Boolean shallow, IDictionary`2 enabledFilters)
   at NHibernate.Impl.SessionImpl.GetFilterQueryPlan(String role, Boolean shallow, String filter, IQueryExpression queryExpression)
   at NHibernate.Impl.SessionImpl.GetFilterQueryPlan(Object collection, QueryParameters parameters, Boolean shallow, String filter, IQueryExpression queryExpression)
   at NHibernate.Impl.SessionImpl.GetFilterQueryPlan(Object collection, IQueryExpression queryExpression, QueryParameters parameters, Boolean shallow)
   at NHibernate.Impl.SessionImpl.CreateFilter(Object collection, IQueryExpression queryExpression)
   at NHibernate.Linq.DefaultQueryProvider.PrepareQuery(Expression expression, IQuery& query)
   at NHibernate.Linq.DefaultQueryProvider.ExecuteList[TResult](Expression expression)
   at NHibernate.Linq.NhQueryable`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Tests.AsQueryableComponentTests.ShouldReturnEntitiesNames_WithAsQueryable()
/
```

**Comment by fredericDelaporte** [comment]
A [collection of components](https://nhibernate.info/doc/nhibernate-reference/components.html#components-incollections) is meant to map data not mapped as entities. So, your use case looks weird.

Do you ave the error also if products are not mapped?

**Comment by fredericDelaporte** [comment]
Actually, as it is a collection of components due to its mapping, `AsQueryable` cannot work: it can work only on collections of entities. But the exception message should be improved.

**Comment by fredericDelaporte** [comment]
Well, the exception message is actually about the trouble:

> collection of values in filter: this

Comes from:
https://github.com/nhibernate/nhibernate-core/blob/7a86566437b8bcad019213f83f9b63c02af559a3/src/NHibernate/Hql/Ast/ANTLR/HqlFilterPreprocessor.cs#L54-L57

`AsQueryable` usage is valid only on collections of entities. Your products collection is not a collection of entities although products are, because it is mapped as a collection of components.
